'use strict';

/**@type {{[k: string]: ModdedTemplateData}} */
let BattlePokedex = {
	deltabulbasaur: {
		num: 727.0,
		species: "DeltaBulbasaur",
		types: ['Fairy', 'Psychic'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 45.0, atk: 49.0, def: 49.0, spa: 65.0, spd: 65.0, spe: 45.0},
		abilities: {0: "Psycho Call", H: "Regenerator"},
		heightm: 0.7,
		weightkg: 6.9,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaivysaur: {
		num: 728.0,
		species: "DeltaIvysaur",
		types: ['Fairy', 'Psychic'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 62.0, def: 63.0, spa: 80.0, spd: 80.0, spe: 60.0},
		abilities: {0: "Psycho Call", 1: "", H: "Regenerator"},
		heightm: 1.0,
		weightkg: 13.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltavenusaur: {
		num: 729.0,
		species: "DeltaVenusaur",
		types: ['Fairy', 'Psychic'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80.0, atk: 82.0, def: 83.0, spa: 100.0, spd: 100.0, spe: 80.0},
		abilities: {0: "Psycho Call", H: "Regenerator"},
		heightm: 2.0,
		weightkg: 100.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacharmander: {
		num: 730.0,
		species: "DeltaCharmander",
		types: ['Ghost', 'Dragon'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 39.0, atk: 52.0, def: 43.0, spa: 60.0, spd: 50.0, spe: 65.0},
		abilities: {0: "Spirit Call", H: "Dark Aura"},
		heightm: 0.6,
		weightkg: 8.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacharmeleon: {
		num: 731.0,
		species: "DeltaCharmeleon",
		types: ['Ghost', 'Dragon'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 58.0, atk: 64.0, def: 58.0, spa: 80.0, spd: 65.0, spe: 80.0},
		abilities: {0: "Spirit Call", H: "Dark Aura"},
		heightm: 1.1,
		weightkg: 19.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacharizard: {
		num: 732.0,
		species: "DeltaCharizard",
		types: ['Ghost', 'Dragon'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 78.0, atk: 84.0, def: 78.0, spa: 109.0, spd: 85.0, spe: 100.0},
		abilities: {0: "Spirit Call", H: "Dark Aura"},
		heightm: 1.7,
		weightkg: 90.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasquirtle: {
		num: 733.0,
		species: "DeltaSquirtle",
		types: ['Dark', 'Fighting'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 44.0, atk: 48.0, def: 65.0, spa: 50.0, spd: 64.0, spe: 43.0},
		abilities: {0: "Shadow Call", 1: "", H: "Pickup"},
		heightm: 0.5,
		weightkg: 9.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltawartortle: {
		num: 734.0,
		species: "DeltaWartortle",
		types: ['Dark', 'Fighting'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 59.0, atk: 63.0, def: 80.0, spa: 65.0, spd: 80.0, spe: 58.0},
		abilities: {0: "Shadow Call", 1: "", H: "Pickup"},
		heightm: 1.0,
		weightkg: 22.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltablastoise: {
		num: 735.0,
		species: "DeltaBlastoise",
		types: ['Dark', 'Fighting'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 79.0, atk: 83.0, def: 100.0, spa: 85.0, spd: 105.0, spe: 78.0},
		abilities: {0: "Shadow Call", 1: "", H: "Pickup"},
		heightm: 1.6,
		weightkg: 85.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapawniard: {
		num: 736.0,
		species: "DeltaPawniard",
		types: ['Flying', 'Fighting'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 45.0, atk: 85.0, def: 70.0, spa: 40.0, spd: 40.0, spe: 60.0},
		abilities: {0: "Defiant", 1: "Frisk", H: "Pickup"},
		heightm: 0.5,
		weightkg: 10.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltabisharp: {
		num: 737.0,
		species: "DeltaBisharp",
		types: ['Flying', 'Fighting'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 65.0, atk: 125.0, def: 100.0, spa: 60.0, spd: 70.0, spe: 70.0},
		abilities: {0: "Frisk", 1: "Defiant", H: "Pickup"},
		heightm: 1.6,
		weightkg: 70.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaralts: {
		num: 738.0,
		species: "DeltaRalts",
		types: ['Electric', 'Ice'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 28.0, atk: 25.0, def: 25.0, spa: 45.0, spd: 35.0, spe: 40.0},
		abilities: {0: "Lightning Rod", 1: "Clear Body", H: "Snow Cloak"},
		heightm: 0.4,
		weightkg: 6.6,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltakirlia: {
		num: 739.0,
		species: "DeltaKirlia",
		types: ['Electric', 'Ice'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 38.0, atk: 35.0, def: 35.0, spa: 65.0, spd: 55.0, spe: 50.0},
		abilities: {0: "Lightning Rod", 1: "Clear Body", H: "Snow Cloak"},
		heightm: 0.8,
		weightkg: 20.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagardevoir: {
		num: 740.0,
		species: "DeltaGardevoir",
		types: ['Electric', 'Ice'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 68.0, atk: 65.0, def: 65.0, spa: 125.0, spd: 115.0, spe: 80.0},
		abilities: {0: "Lightning Rod", 1: "Clear Body", H: "Snow Cloak"},
		heightm: 1.6,
		weightkg: 48.4,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagallade: {
		num: 741.0,
		species: "DeltaGallade",
		types: ['Electric', 'Ice'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 68.0, atk: 125.0, def: 65.0, spa: 65.0, spd: 115.0, spe: 80.0},
		abilities: {0: "Volt Absorb", H: "Ice Body"},
		heightm: 1.6,
		weightkg: 52.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasunkern: {
		num: 742.0,
		species: "DeltaSunkern",
		types: ['Fire', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 30.0, atk: 30.0, def: 30.0, spa: 30.0, spd: 30.0, spe: 30.0},
		abilities: {0: "Flame Body", 1: "Analytic", H: "Poison Point"},
		heightm: 0.3,
		weightkg: 1.8,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasunflora: {
		num: 743.0,
		species: "DeltaSunflora",
		types: ['Fire', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 75.0, atk: 75.0, def: 55.0, spa: 105.0, spd: 85.0, spe: 30.0},
		abilities: {0: "Flame Body", 1: "Analytic", H: "Poison Point"},
		heightm: 0.8,
		weightkg: 8.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltabergmite: {
		num: 744.0,
		species: "DeltaBergmite",
		types: ['Rock'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 55.0, atk: 69.0, def: 85.0, spa: 32.0, spd: 35.0, spe: 28.0},
		abilities: {0: "Solid Rock", 1: "Battle Armor", H: "Sand Stream"},
		heightm: 1.0,
		weightkg: 99.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaavalugg: {
		num: 745.0,
		species: "DeltaAvalugg",
		types: ['Rock', 'Dragon'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 95.0, atk: 117.0, def: 184.0, spa: 44.0, spd: 46.0, spe: 28.0},
		abilities: {0: "Solid Rock", 1: "Battle Armor", H: "Sand Stream"},
		heightm: 2.0,
		weightkg: 505.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltascyther: {
		num: 746.0,
		species: "DeltaScyther",
		types: ['Ice', 'Fighting'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 110.0, def: 80.0, spa: 55.0, spd: 80.0, spe: 105.0},
		abilities: {0: "Hustle", 1: "Ice Cleats", H: "Super Luck"},
		heightm: 1.5,
		weightkg: 56.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltascizor: {
		num: 747.0,
		species: "DeltaScizor",
		types: ['Ice', 'Fighting'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 130.0, def: 100.0, spa: 55.0, spd: 80.0, spe: 65.0},
		abilities: {0: "Scrappy", 1: "Ice Cleats", H: "Super Luck"},
		heightm: 1.8,
		weightkg: 118.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltascraggy: {
		num: 748.0,
		species: "DeltaScraggy",
		types: ['Grass'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 50.0, atk: 75.0, def: 70.0, spa: 35.0, spd: 70.0, spe: 48.0},
		abilities: {0: "Rough Skin", 1: "Rivalry", H: "Anger Point"},
		heightm: 0.6,
		weightkg: 11.8,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltascrafty: {
		num: 749.0,
		species: "DeltaScrafty",
		types: ['Grass'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 65.0, atk: 90.0, def: 115.0, spa: 45.0, spd: 115.0, spe: 58.0},
		abilities: {0: "Rough Skin", 1: "Rivalry", H: "Anger Point"},
		heightm: 1.1,
		weightkg: 30.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacombee: {
		num: 750.0,
		species: "DeltaCombee",
		types: ['Steel', 'fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 30.0, atk: 30.0, def: 42.0, spa: 30.0, spd: 42.0, spe: 70.0},
		abilities: {0: "Levitate", H: "Speed Boost"},
		heightm: 0.3,
		weightkg: 11.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltavespiquen: {
		num: 751.0,
		species: "DeltaVespiquen",
		types: ['Steel', 'fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 80.0, def: 102.0, spa: 80.0, spd: 102.0, spe: 40.0},
		abilities: {0: "Levitate", H: "Speed Boost"},
		heightm: 1.2,
		weightkg: 38.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltakoffing: {
		num: 752.0,
		species: "DeltaKoffing",
		types: ['Electric', 'Flying'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 40.0, atk: 65.0, def: 95.0, spa: 60.0, spd: 45.0, spe: 35.0},
		abilities: {0: "Cloud Nine", 1: "Pickup", H: "Volt Absorb"},
		heightm: 0.6,
		weightkg: 1.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaweezing: {
		num: 753.0,
		species: "DeltaWeezing",
		types: ['Electric', 'Flying'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 65.0, atk: 90.0, def: 120.0, spa: 85.0, spd: 70.0, spe: 60.0},
		abilities: {0: "Cloud Nine", 1: "Pickup", H: "Volt Absorb"},
		heightm: 1.2,
		weightkg: 9.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapurrloin: {
		num: 754.0,
		species: "DeltaPurrloin",
		types: ['Ghost', 'Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 41.0, atk: 50.0, def: 37.0, spa: 50.0, spd: 37.0, spe: 66.0},
		abilities: {0: "Illusion", 1: "Unnerve", H: "Lightning Rod"},
		heightm: 0.4,
		weightkg: 10.1,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaliepard: {
		num: 755.0,
		species: "DeltaLiepard",
		types: ['Ghost', 'Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 64.0, atk: 88.0, def: 50.0, spa: 88.0, spd: 50.0, spe: 106.0},
		abilities: {0: "Illusion", 1: "Unnerve", H: "Bulletproof"},
		heightm: 1.1,
		weightkg: 37.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaphantump: {
		num: 756.0,
		species: "DeltaPhantump",
		types: ['Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 43.0, atk: 70.0, def: 48.0, spa: 50.0, spd: 60.0, spe: 38.0},
		abilities: {0: "Snow Warning", 1: "Overcoat", H: "Snow Cloak"},
		heightm: 0.4,
		weightkg: 7.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatrevenant: {
		num: 757.0,
		species: "DeltaTrevenant",
		types: ['Fairy', 'fighting'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 85.0, atk: 110.0, def: 76.0, spa: 65.0, spd: 82.0, spe: 56.0},
		abilities: {0: "Snow Warning", 1: "Overcoat", H: "Snow Cloak"},
		heightm: 1.5,
		weightkg: 71.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasnorunt: {
		num: 758.0,
		species: "DeltaSnorunt",
		types: ['Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 50.0, atk: 50.0, def: 50.0, spa: 50.0, spd: 50.0, spe: 50.0},
		abilities: {0: "White Smoke", H: "Flash Fire"},
		heightm: 0.7,
		weightkg: 16.8,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaglalie: {
		num: 759.0,
		species: "DeltaGlalie",
		types: ['Fire', 'rock'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80.0, atk: 80.0, def: 80.0, spa: 80.0, spd: 80.0, spe: 80.0},
		abilities: {0: "Rock Head", H: "Flash Fire"},
		heightm: 1.5,
		weightkg: 256.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltafroslass: {
		num: 760.0,
		species: "DeltaFroslass",
		types: ['Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 80.0, def: 70.0, spa: 80.0, spd: 70.0, spe: 110.0},
		abilities: {0: "Competitive", H: "Flash Fire"},
		heightm: 1.3,
		weightkg: 26.6,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltashinx: {
		num: 761.0,
		species: "DeltaShinx",
		types: ['Steel', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 45.0, atk: 65.0, def: 34.0, spa: 40.0, spd: 34.0, spe: 45.0},
		abilities: {0: "Sniper", 1: "Poison Touch", H: "Pickup"},
		heightm: 0.5,
		weightkg: 19.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaluxio: {
		num: 762.0,
		species: "DeltaLuxio",
		types: ['Steel', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 85.0, def: 49.0, spa: 60.0, spd: 49.0, spe: 60.0},
		abilities: {0: "Poison Touch", 1: "Sniper", H: "Pickup"},
		heightm: 0.9,
		weightkg: 30.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaluxray: {
		num: 763.0,
		species: "DeltaLuxray",
		types: ['Steel', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80.0, atk: 120.0, def: 79.0, spa: 95.0, spd: 79.0, spe: 70.0},
		abilities: {0: "Poison Touch", 1: "Sniper", H: "Pickup"},
		heightm: 1.4,
		weightkg: 42.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltanoibat: {
		num: 764.0,
		species: "DeltaNoibat",
		types: ['Grass', 'Steel'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 40.0, atk: 30.0, def: 35.0, spa: 45.0, spd: 40.0, spe: 55.0},
		abilities: {0: "Chlorophyll", 1: "Natural Cure", H: "Solar Power"},
		heightm: 0.5,
		weightkg: 8.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltanoivern: {
		num: 765.0,
		species: "DeltaNoivern",
		types: ['Grass', 'Steel'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 85.0, atk: 70.0, def: 80.0, spa: 97.0, spd: 80.0, spe: 123.0},
		abilities: {0: "Chlorophyll", 1: "Solar Power", H: "Flower Gift"},
		heightm: 1.5,
		weightkg: 85.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltabudew: {
		num: 766.0,
		species: "DeltaBudew",
		types: ['Dark', 'Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 40.0, atk: 30.0, def: 35.0, spa: 50.0, spd: 70.0, spe: 55.0},
		abilities: {0: "Pickup", 1: "Pickup", H: "Inner Focus"},
		heightm: 0.2,
		weightkg: 1.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaroselia: {
		num: 767.0,
		species: "DeltaRoselia",
		types: ['Dark', 'Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 50.0, atk: 60.0, def: 45.0, spa: 100.0, spd: 80.0, spe: 65.0},
		abilities: {0: "Pickup", 1: "Pickup", H: "Limber"},
		heightm: 0.3,
		weightkg: 2.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaroserade: {
		num: 768.0,
		species: "DeltaRoserade",
		types: ['Dark', 'Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 70.0, def: 55.0, spa: 125.0, spd: 105.0, spe: 90.0},
		abilities: {0: "Pickup", 1: "Pickup", H: "Limber"},
		heightm: 0.9,
		weightkg: 14.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadrifloon: {
		num: 769.0,
		species: "DeltaDrifloon",
		types: ['Fire', 'Flying'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 90.0, atk: 50.0, def: 34.0, spa: 60.0, spd: 44.0, spe: 70.0},
		abilities: {0: "Flash Fire", 1: "Vital Spirit", H: "No Guard"},
		heightm: 0.4,
		weightkg: 1.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadrifblim: {
		num: 770.0,
		species: "DeltaDrifblim",
		types: ['Fire', 'Flying'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 150.0, atk: 80.0, def: 44.0, spa: 90.0, spd: 54.0, spe: 80.0},
		abilities: {0: "Flash Fire", 1: "Vital Spirit", H: "No Guard"},
		heightm: 1.2,
		weightkg: 15.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagrimer: {
		num: 771.0,
		species: "DeltaGrimer",
		types: ['Ground'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80.0, atk: 80.0, def: 50.0, spa: 40.0, spd: 50.0, spe: 25.0},
		abilities: {0: "Sap Sipper", H: "Water Absorb"},
		heightm: 0.9,
		weightkg: 30.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamuk: {
		num: 772.0,
		species: "DeltaMuk",
		types: ['Ground'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 105.0, atk: 105.0, def: 75.0, spa: 65.0, spd: 100.0, spe: 50.0},
		abilities: {0: "Sap Sipper", 1: "Pickup", H: "Water Absorb"},
		heightm: 1.2,
		weightkg: 30.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltawooper: {
		num: 773.0,
		species: "DeltaWooper",
		types: ['Grass', 'Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 55.0, atk: 45.0, def: 45.0, spa: 25.0, spd: 25.0, spe: 15.0},
		abilities: {0: "Pickpocket", 1: "Flash Fire", H: "Harvest"},
		heightm: 0.4,
		weightkg: 8.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaquagsire: {
		num: 774.0,
		species: "DeltaQuagsire",
		types: ['Grass', 'Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 95.0, atk: 85.0, def: 85.0, spa: 65.0, spd: 65.0, spe: 35.0},
		abilities: {0: "Pickpocket", 1: "Flash Fire", H: "Harvest"},
		heightm: 1.4,
		weightkg: 75.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamunchlax: {
		num: 775.0,
		species: "DeltaMunchlax",
		types: ['Grass'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 135.0, atk: 85.0, def: 40.0, spa: 40.0, spd: 85.0, spe: 5.0},
		abilities: {0: "Overcoat", 1: "Thick Fat", H: "Adaptability"},
		heightm: 0.6,
		weightkg: 105.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasnorlax: {
		num: 776.0,
		species: "DeltaSnorlax",
		types: ['Grass'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 160.0, atk: 110.0, def: 65.0, spa: 65.0, spd: 110.0, spe: 30.0},
		abilities: {0: "Overcoat", 1: "Thick Fat", H: "Adaptability"},
		heightm: 2.1,
		weightkg: 460.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamisdreavus: {
		num: 777.0,
		species: "DeltaMisdreavus",
		types: ['Ice', 'Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 60.0, def: 60.0, spa: 85.0, spd: 85.0, spe: 85.0},
		abilities: {0: "Magic Guard", H: "Pickup"},
		heightm: 0.7,
		weightkg: 1.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamismagius: {
		num: 778.0,
		species: "DeltaMismagius",
		types: ['Ice', 'Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 60.0, def: 60.0, spa: 105.0, spd: 105.0, spe: 105.0},
		abilities: {0: "Magic Guard", H: "Pickup"},
		heightm: 0.9,
		weightkg: 4.4,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacyndaquil: {
		num: 779.0,
		species: "DeltaCyndaquil",
		types: ['Electric'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 39.0, atk: 52.0, def: 43.0, spa: 60.0, spd: 50.0, spe: 65.0},
		abilities: {0: "Static", H: "Lightning Rod"},
		heightm: 0.5,
		weightkg: 7.9,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaquilava: {
		num: 780.0,
		species: "DeltaQuilava",
		types: ['Electric', 'Steel'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 58.0, atk: 64.0, def: 58.0, spa: 80.0, spd: 65.0, spe: 80.0},
		abilities: {0: "Static", H: "Lightning Rod"},
		heightm: 0.9,
		weightkg: 28.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatyphlosion: {
		num: 781.0,
		species: "DeltaTyphlosion",
		types: ['Electric', 'Steel'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 78.0, atk: 84.0, def: 78.0, spa: 109.0, spd: 85.0, spe: 100.0},
		abilities: {0: "Motor Drive", H: "Lightning Rod"},
		heightm: 1.7,
		weightkg: 159.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatreecko: {
		num: 782.0,
		species: "DeltaTreecko",
		types: ['Normal', 'Fighting'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 40.0, atk: 45.0, def: 35.0, spa: 65.0, spd: 55.0, spe: 70.0},
		abilities: {0: "Inner Focus", H: "Iron Fist"},
		heightm: 0.5,
		weightkg: 5.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagrovyle: {
		num: 783.0,
		species: "DeltaGrovyle",
		types: ['Normal', 'Fighting'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 50.0, atk: 65.0, def: 45.0, spa: 85.0, spd: 65.0, spe: 95.0},
		abilities: {0: "Inner Focus", H: "Iron Fist"},
		heightm: 0.9,
		weightkg: 21.6,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasceptile: {
		num: 784.0,
		species: "DeltaSceptile",
		types: ['Dragon', 'Fighting'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 85.0, def: 65.0, spa: 105.0, spd: 85.0, spe: 120.0},
		abilities: {0: "Inner Focus", H: "Iron Fist"},
		heightm: 1.7,
		weightkg: 52.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatorchic: {
		num: 785.0,
		species: "DeltaTorchic",
		types: ['Psychic'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 45.0, atk: 60.0, def: 40.0, spa: 70.0, spd: 50.0, spe: 45.0},
		abilities: {0: "Keen Eye", H: "Rivalry"},
		heightm: 0.4,
		weightkg: 2.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacombusken: {
		num: 786.0,
		species: "DeltaCombusken",
		types: ['Psychic'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 85.0, def: 60.0, spa: 85.0, spd: 60.0, spe: 55.0},
		abilities: {0: "Keen Eye", H: "Rivalry"},
		heightm: 0.9,
		weightkg: 19.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltablaziken: {
		num: 787.0,
		species: "DeltaBlaziken",
		types: ['Psychic', 'Flying'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80.0, atk: 120.0, def: 70.0, spa: 110.0, spd: 70.0, spe: 80.0},
		abilities: {0: "Keen Eye", H: "Gale Wings"},
		heightm: 1.9,
		weightkg: 52.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaturtwig: {
		num: 788.0,
		species: "DeltaTurtwig",
		types: ['Water', 'Ground'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 55.0, atk: 68.0, def: 64.0, spa: 45.0, spd: 55.0, spe: 31.0},
		abilities: {0: "Water Absorb", H: "Swift Swim"},
		heightm: 0.4,
		weightkg: 10.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagrotle: {
		num: 789.0,
		species: "DeltaGrotle",
		types: ['Water', 'Ground'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 75.0, atk: 89.0, def: 85.0, spa: 55.0, spd: 65.0, spe: 36.0},
		abilities: {0: "Water Absorb", H: "Swift Swim"},
		heightm: 1.1,
		weightkg: 97.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatorterra: {
		num: 790.0,
		species: "DeltaTorterra",
		types: ['Water', 'Ground'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 95.0, atk: 109.0, def: 105.0, spa: 75.0, spd: 85.0, spe: 56.0},
		abilities: {0: "Water Absorb", H: "Swift Swim"},
		heightm: 2.2,
		weightkg: 310.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasnivy: {
		num: 791.0,
		species: "DeltaSnivy",
		types: ['Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 45.0, atk: 45.0, def: 55.0, spa: 45.0, spd: 55.0, spe: 63.0},
		abilities: {0: "Multiscale", H: "Hydration"},
		heightm: 0.6,
		weightkg: 8.1,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaservine: {
		num: 792.0,
		species: "DeltaServine",
		types: ['Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 60.0, def: 75.0, spa: 60.0, spd: 75.0, spe: 83.0},
		abilities: {0: "Multiscale", H: "Hydration"},
		heightm: 0.8,
		weightkg: 16.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaserperior: {
		num: 793.0,
		species: "DeltaSerperior",
		types: ['Water', 'Dragon'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 75.0, atk: 75.0, def: 95.0, spa: 75.0, spd: 95.0, spe: 113.0},
		abilities: {0: "Multiscale", H: "Drizzle"},
		heightm: 3.3,
		weightkg: 63.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltafroakie: {
		num: 794.0,
		species: "DeltaFroakie",
		types: ['Grass'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 41.0, atk: 56.0, def: 40.0, spa: 62.0, spd: 44.0, spe: 71.0},
		abilities: {0: "Steadfast", H: "Prankster"},
		heightm: 0.3,
		weightkg: 7.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltafrogadier: {
		num: 795.0,
		species: "DeltaFrogadier",
		types: ['Grass'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 54.0, atk: 63.0, def: 52.0, spa: 83.0, spd: 56.0, spe: 97.0},
		abilities: {0: "Steadfast", H: "Prankster"},
		heightm: 0.6,
		weightkg: 10.9,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagreninja: {
		num: 796.0,
		species: "DeltaGreninja",
		types: ['Grass', 'Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 72.0, atk: 95.0, def: 67.0, spa: 103.0, spd: 71.0, spe: 122.0},
		abilities: {0: "Steadfast", H: "Prankster"},
		heightm: 1.5,
		weightkg: 40.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapidgey: {
		num: 797.0,
		species: "DeltaPidgey",
		types: ['Dark', 'Dragon'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 40.0, atk: 45.0, def: 40.0, spa: 35.0, spd: 35.0, spe: 56.0},
		abilities: {0: "Intimidate", 1: "Early Bird", H: "Marvel Scale"},
		heightm: 0.3,
		weightkg: 1.8,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapidgeotto: {
		num: 798.0,
		species: "DeltaPidgeotto",
		types: ['Dark', 'Dragon'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 63.0, atk: 60.0, def: 55.0, spa: 50.0, spd: 50.0, spe: 71.0},
		abilities: {0: "Intimidate", 1: "Early Bird", H: "Marvel Scale"},
		heightm: 1.1,
		weightkg: 30.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapidgeot: {
		num: 799.0,
		species: "DeltaPidgeot",
		types: ['Dark', 'Dragon'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 83.0, atk: 80.0, def: 75.0, spa: 70.0, spd: 70.0, spe: 101.0},
		abilities: {0: "Intimidate", 1: "Keen Eye", H: "Marvel Scale"},
		heightm: 1.5,
		weightkg: 39.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadiglett: {
		num: 800.0,
		species: "DeltaDiglett",
		types: ['Ice', 'Normal'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 10.0, atk: 55.0, def: 25.0, spa: 35.0, spd: 45.0, spe: 95.0},
		abilities: {0: "Snow Cloak", 1: "Ice Cleats", H: "Fur Coat"},
		heightm: 0.2,
		weightkg: 0.8,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadugtrio: {
		num: 801.0,
		species: "DeltaDugtrio",
		types: ['Ice', 'Normal'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 35.0, atk: 80.0, def: 50.0, spa: 50.0, spd: 70.0, spe: 120.0},
		abilities: {0: "Snow Cloak", 1: "Ice Cleats", H: "Fur Coat"},
		heightm: 0.7,
		weightkg: 33.3,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagrowlithe: {
		num: 802.0,
		species: "DeltaGrowlithe",
		types: ['Normal', 'Dragon'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 55.0, atk: 70.0, def: 45.0, spa: 70.0, spd: 50.0, spe: 60.0},
		abilities: {0: "Inner Focus", 1: "Intimidate", H: "Multiscale"},
		heightm: 0.7,
		weightkg: 19.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaarcanine: {
		num: 803.0,
		species: "DeltaArcanine",
		types: ['Normal', 'Dragon'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 90.0, atk: 110.0, def: 80.0, spa: 100.0, spd: 80.0, spe: 95.0},
		abilities: {0: "Inner Focus", 1: "Intimidate", H: "Multiscale"},
		heightm: 1.9,
		weightkg: 155.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltageodude: {
		num: 804.0,
		species: "DeltaGeodude",
		types: ['Psychic', 'Rock'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 40.0, atk: 80.0, def: 100.0, spa: 30.0, spd: 30.0, spe: 20.0},
		abilities: {0: "Regenerator", 1: "Sap Sipper", H: "Magic Bounce"},
		heightm: 0.4,
		weightkg: 20.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagraveler: {
		num: 805.0,
		species: "DeltaGraveler",
		types: ['Psychic', 'Rock'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 55.0, atk: 95.0, def: 115.0, spa: 45.0, spd: 45.0, spe: 35.0},
		abilities: {0: "Regenerator", 1: "Sap Sipper", H: "Magic Bounce"},
		heightm: 1.0,
		weightkg: 105.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagolem: {
		num: 806.0,
		species: "DeltaGolem",
		types: ['Psychic', 'Rock'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80.0, atk: 120.0, def: 130.0, spa: 55.0, spd: 65.0, spe: 45.0},
		abilities: {0: "Regenerator", 1: "Sap Sipper", H: "Magic Bounce"},
		heightm: 1.4,
		weightkg: 300.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatentacool: {
		num: 807.0,
		species: "DeltaTentacool",
		types: ['Grass', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 40.0, atk: 40.0, def: 35.0, spa: 50.0, spd: 100.0, spe: 70.0},
		abilities: {0: "Regenerator", 1: "Poison Touch", H: "Overgrow"},
		heightm: 0.9,
		weightkg: 45.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatentacruel: {
		num: 808.0,
		species: "DeltaTentacruel",
		types: ['Grass', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80.0, atk: 70.0, def: 65.0, spa: 80.0, spd: 120.0, spe: 100.0},
		abilities: {0: "Regenerator", 1: "Poison Touch", H: "Overgrow"},
		heightm: 1.6,
		weightkg: 55.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadoduo: {
		num: 809.0,
		species: "DeltaDoduo",
		types: ['Psychic'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 35.0, atk: 85.0, def: 45.0, spa: 35.0, spd: 35.0, spe: 75.0},
		abilities: {0: "Compoundeyes", 1: "Trace", H: "Psycho Call"},
		heightm: 1.4,
		weightkg: 39.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadodrio: {
		num: 810.0,
		species: "DeltaDodrio",
		types: ['Psychic'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 110.0, def: 70.0, spa: 60.0, spd: 60.0, spe: 100.0},
		abilities: {0: "Compoundeyes", 1: "Trace", H: "Psycho Call"},
		heightm: 1.8,
		weightkg: 85.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatangela: {
		num: 811.0,
		species: "DeltaTangela",
		types: ['Ground'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 65.0, atk: 55.0, def: 115.0, spa: 100.0, spd: 40.0, spe: 60.0},
		abilities: {0: "Dry Skin", 1: "Sand Force", H: "Rough Skin"},
		heightm: 1.0,
		weightkg: 35.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatangrowth: {
		num: 812.0,
		species: "DeltaTangrowth",
		types: ['Ground', 'Fighting'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 100.0, atk: 100.0, def: 125.0, spa: 110.0, spd: 50.0, spe: 50.0},
		abilities: {0: "Dry Skin", 1: "Sand Force", H: "Rough Skin"},
		heightm: 2.0,
		weightkg: 128.6,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaditto: {
		num: 813.0,
		species: "DeltaDitto",
		types: ['Normal'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 48.0, atk: 48.0, def: 48.0, spa: 48.0, spd: 48.0, spe: 48.0},
		abilities: {0: "Protean"},
		heightm: 0.3,
		weightkg: 4.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltakabuto: {
		num: 814.0,
		species: "DeltaKabuto",
		types: ['Bug', 'Dark'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 30.0, atk: 80.0, def: 95.0, spa: 55.0, spd: 45.0, spe: 55.0},
		abilities: {0: "Swarm", 1: "Unnerve", H: "Tough Claws"},
		heightm: 0.5,
		weightkg: 11.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltakabutops: {
		num: 815.0,
		species: "DeltaKabutops",
		types: ['Bug', 'Dark'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 115.0, def: 105.0, spa: 65.0, spd: 70.0, spe: 80.0},
		abilities: {0: "Swarm", 1: "Unnerve", H: "Tough Claws"},
		heightm: 1.3,
		weightkg: 40.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadratini: {
		num: 816.0,
		species: "DeltaDratini",
		types: ['Electric', 'Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 41.0, atk: 64.0, def: 45.0, spa: 50.0, spd: 50.0, spe: 50.0},
		abilities: {0: "Swift Swim", H: "Volt Absorb"},
		heightm: 1.8,
		weightkg: 3.3,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadragonair: {
		num: 817.0,
		species: "DeltaDragonair",
		types: ['Electric', 'Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 61.0, atk: 84.0, def: 65.0, spa: 70.0, spd: 70.0, spe: 70.0},
		abilities: {0: "Swift Swim", H: "Volt Absorb"},
		heightm: 4.0,
		weightkg: 16.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadragonite: {
		num: 818.0,
		species: "DeltaDragonite",
		types: ['Electric', 'Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 91.0, atk: 134.0, def: 95.0, spa: 100.0, spd: 100.0, spe: 80.0},
		abilities: {0: "Swift Swim", H: "Volt Absorb"},
		heightm: 2.2,
		weightkg: 210.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltahoothoot: {
		num: 819.0,
		species: "DeltaHoothoot",
		types: ['Ice', 'Flying'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 30.0, def: 30.0, spa: 36.0, spd: 56.0, spe: 50.0},
		abilities: {0: "Snow Cloak", 1: "Keen Eye", H: "No Guard"},
		heightm: 0.7,
		weightkg: 21.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltanoctowl: {
		num: 820.0,
		species: "DeltaNoctowl",
		types: ['Ice', 'Flying'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 100.0, atk: 50.0, def: 50.0, spa: 76.0, spd: 96.0, spe: 70.0},
		abilities: {0: "Snow Cloak", 1: "Keen Eye", H: "No Guard"},
		heightm: 1.6,
		weightkg: 40.8,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltachinchou: {
		num: 821.0,
		species: "DeltaChinchou",
		types: ['Ghost', 'Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 75.0, atk: 38.0, def: 38.0, spa: 56.0, spd: 56.0, spe: 67.0},
		abilities: {0: "Flash Fire", 1: "Illuminate", H: "Levitate"},
		heightm: 0.5,
		weightkg: 12.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalanturn: {
		num: 822.0,
		species: "DeltaLanturn",
		types: ['Ghost', 'Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 125.0, atk: 58.0, def: 58.0, spa: 76.0, spd: 76.0, spe: 67.0},
		abilities: {0: "Flash Fire", 1: "Illuminate", H: "Levitate"},
		heightm: 1.2,
		weightkg: 22.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapichu: {
		num: 823.0,
		species: "DeltaPichu",
		types: ['Flying', 'Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 20.0, atk: 40.0, def: 15.0, spa: 35.0, spd: 35.0, spe: 60.0},
		abilities: {0: "Cute Charm", 1: "Cloud Nine", H: "Gale Wings"},
		heightm: 0.3,
		weightkg: 2.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapikachu: {
		num: 824.0,
		species: "DeltaPikachu",
		types: ['Flying', 'Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 35.0, atk: 55.0, def: 30.0, spa: 50.0, spd: 40.0, spe: 90.0},
		abilities: {0: "Cute Charm", 1: "Cloud Nine", H: "Gale Wings"},
		heightm: 0.4,
		weightkg: 6.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaraichu: {
		num: 825.0,
		species: "DeltaRaichu",
		types: ['Flying', 'Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 90.0, def: 55.0, spa: 90.0, spd: 80.0, spe: 110.0},
		abilities: {0: "Cute Charm", 1: "Cloud Nine", H: "Gale Wings"},
		heightm: 0.8,
		weightkg: 30.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaaipom: {
		num: 826.0,
		species: "DeltaAipom",
		types: ['Ghost', 'Normal'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 55.0, atk: 70.0, def: 55.0, spa: 40.0, spd: 55.0, spe: 85.0},
		abilities: {0: "Cursed Body", 1: "Rattled", H: "Technician"},
		heightm: 0.8,
		weightkg: 11.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaambipom: {
		num: 827.0,
		species: "DeltaAmbipom",
		types: ['Ghost', 'Normal'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 75.0, atk: 100.0, def: 66.0, spa: 60.0, spd: 66.0, spe: 115.0},
		abilities: {0: "Cursed Body", 1: "Infiltrator", H: "Technician"},
		heightm: 1.2,
		weightkg: 20.3,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltayanma: {
		num: 828.0,
		species: "DeltaYanma",
		types: ['Grass', 'Flying'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 65.0, atk: 65.0, def: 45.0, spa: 75.0, spd: 45.0, spe: 95.0},
		abilities: {0: "Adaptability", 1: "Leaf Guard", H: "Natural Cure"},
		heightm: 1.2,
		weightkg: 38.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltayanmega: {
		num: 829.0,
		species: "DeltaYanmega",
		types: ['Grass', 'Flying'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 86.0, atk: 76.0, def: 86.0, spa: 116.0, spd: 56.0, spe: 95.0},
		abilities: {0: "Adaptability", 1: "Chlorophyll", H: "Natural Cure"},
		heightm: 1.9,
		weightkg: 51.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagirafarig: {
		num: 830.0,
		species: "DeltaGirafarig",
		types: ['Steel', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 80.0, def: 65.0, spa: 90.0, spd: 65.0, spe: 85.0},
		abilities: {0: "Anger Point", 1: "Stench", H: "Intimidate"},
		heightm: 1.5,
		weightkg: 41.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadunsparce: {
		num: 831.0,
		species: "DeltaDunsparce",
		types: ['Bug', 'Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 100.0, atk: 70.0, def: 70.0, spa: 65.0, spd: 65.0, spe: 45.0},
		abilities: {0: "Hyper Cutter", 1: "Swift Swim", H: "Skill Link"},
		heightm: 1.5,
		weightkg: 14.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltashuckle: {
		num: 832.0,
		species: "DeltaShuckle",
		types: ['Fighting', 'Steel'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 20.0, atk: 10.0, def: 230.0, spa: 10.0, spd: 230.0, spe: 5.0},
		abilities: {0: "Sturdy", 1: "No Guard", H: "Iron Barbs"},
		heightm: 0.6,
		weightkg: 20.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaremoraid: {
		num: 833.0,
		species: "DeltaRemoraid",
		types: ['Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 35.0, atk: 65.0, def: 35.0, spa: 65.0, spd: 35.0, spe: 65.0},
		abilities: {0: "Heatproof", 1: "White Smoke", H: "Contrary"},
		heightm: 0.6,
		weightkg: 12.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaoctillery: {
		num: 834.0,
		species: "DeltaOctillery",
		types: ['Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 75.0, atk: 105.0, def: 75.0, spa: 105.0, spd: 75.0, spe: 45.0},
		abilities: {0: "Heatproof", 1: "White Smoke", H: "Contrary"},
		heightm: 0.9,
		weightkg: 28.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaelekid: {
		num: 835.0,
		species: "DeltaElekid",
		types: ['Rock'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 45.0, atk: 63.0, def: 37.0, spa: 65.0, spd: 55.0, spe: 95.0},
		abilities: {0: "Inner Focus", H: "Battle Armor"},
		heightm: 0.6,
		weightkg: 23.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaelectabuzz: {
		num: 836.0,
		species: "DeltaElectabuzz",
		types: ['Rock'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 65.0, atk: 83.0, def: 57.0, spa: 95.0, spd: 85.0, spe: 105.0},
		abilities: {0: "Inner Focus", H: "Battle Armor"},
		heightm: 1.1,
		weightkg: 30.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaelectivire: {
		num: 837.0,
		species: "DeltaElectivire",
		types: ['Rock', 'Dragon'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 75.0, atk: 123.0, def: 67.0, spa: 95.0, spd: 85.0, spe: 95.0},
		abilities: {0: "Pickup", H: "Sturdy"},
		heightm: 1.8,
		weightkg: 138.6,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamagby: {
		num: 838.0,
		species: "DeltaMagby",
		types: ['Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 45.0, atk: 75.0, def: 37.0, spa: 70.0, spd: 55.0, spe: 83.0},
		abilities: {0: "Swift Swim", H: "Rain Dish"},
		heightm: 0.7,
		weightkg: 21.4,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamagmar: {
		num: 839.0,
		species: "DeltaMagmar",
		types: ['Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 65.0, atk: 95.0, def: 57.0, spa: 100.0, spd: 85.0, spe: 93.0},
		abilities: {0: "Swift Swim", H: "Rain Dish"},
		heightm: 1.3,
		weightkg: 44.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamagmortar: {
		num: 840.0,
		species: "DeltaMagmortar",
		types: ['Water', 'Steel'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 75.0, atk: 95.0, def: 67.0, spa: 125.0, spd: 95.0, spe: 83.0},
		abilities: {0: "Mega Launcher", H: "Filter"},
		heightm: 1.6,
		weightkg: 68.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalotad: {
		num: 841.0,
		species: "DeltaLotad",
		types: ['Psychic', 'Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 40.0, atk: 30.0, def: 30.0, spa: 40.0, spd: 50.0, spe: 30.0},
		abilities: {0: "Magic Bounce", 1: "Synchronize", H: "Unaware"},
		heightm: 0.5,
		weightkg: 2.6,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalombre: {
		num: 842.0,
		species: "DeltaLombre",
		types: ['Psychic', 'Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 50.0, def: 50.0, spa: 60.0, spd: 70.0, spe: 50.0},
		abilities: {0: "Magic Bounce", 1: "Synchronize", H: "Unaware"},
		heightm: 1.2,
		weightkg: 32.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaludicolo: {
		num: 843.0,
		species: "DeltaLudicolo",
		types: ['Psychic', 'Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80.0, atk: 70.0, def: 70.0, spa: 90.0, spd: 100.0, spe: 70.0},
		abilities: {0: "Magic Bounce", 1: "Synchronize", H: "Unaware"},
		heightm: 1.5,
		weightkg: 55.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaseedot: {
		num: 844.0,
		species: "DeltaSeedot",
		types: ['Electric'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 40.0, atk: 40.0, def: 50.0, spa: 30.0, spd: 30.0, spe: 30.0},
		abilities: {0: "Volt Absorb", 1: "Minus", H: "Competitive"},
		heightm: 0.5,
		weightkg: 4.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltanuzleaf: {
		num: 845.0,
		species: "DeltaNuzleaf",
		types: ['Electric'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 70.0, def: 40.0, spa: 60.0, spd: 40.0, spe: 60.0},
		abilities: {0: "Volt Absorb", 1: "Minus", H: "Competitive"},
		heightm: 1.0,
		weightkg: 28.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltashiftry: {
		num: 846.0,
		species: "DeltaShiftry",
		types: ['Electric'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 90.0, atk: 100.0, def: 60.0, spa: 90.0, spd: 60.0, spe: 80.0},
		abilities: {0: "Volt Absorb", 1: "Minus", H: "Competitive"},
		heightm: 1.3,
		weightkg: 59.6,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasableye: {
		num: 847.0,
		species: "DeltaSableye",
		types: ['Fire', 'Rock'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 50.0, atk: 75.0, def: 75.0, spa: 65.0, spd: 65.0, spe: 50.0},
		abilities: {0: "Solid Rock", 1: "Weak Armor", H: "Unburden"},
		heightm: 0.5,
		weightkg: 11.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamawile: {
		num: 848.0,
		species: "DeltaMawile",
		types: ['Grass', 'Dark'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 50.0, atk: 85.0, def: 85.0, spa: 55.0, spd: 55.0, spe: 50.0},
		abilities: {0: "Serene Grace", 1: "Aroma Veil", H: "Immunity"},
		heightm: 0.6,
		weightkg: 11.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaaron: {
		num: 849.0,
		species: "DeltaAron",
		types: ['Fire', 'Steel'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 50.0, atk: 70.0, def: 100.0, spa: 40.0, spd: 40.0, spe: 30.0},
		abilities: {0: "Flame Body", 1: "Drought", H: "Heavy Metal"},
		heightm: 0.4,
		weightkg: 60.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalairon: {
		num: 850.0,
		species: "DeltaLairon",
		types: ['Fire', 'Steel'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 90.0, def: 140.0, spa: 50.0, spd: 50.0, spe: 40.0},
		abilities: {0: "Flame Body", 1: "Drought", H: "Heavy Metal"},
		heightm: 0.9,
		weightkg: 120.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaaggron: {
		num: 851.0,
		species: "DeltaAggron",
		types: ['Fire', 'Steel'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 110.0, def: 180.0, spa: 60.0, spd: 60.0, spe: 50.0},
		abilities: {0: "Flame Body", 1: "Drought", H: "Heavy Metal"},
		heightm: 2.1,
		weightkg: 360.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltameditite: {
		num: 852.0,
		species: "DeltaMeditite",
		types: ['Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 30.0, atk: 40.0, def: 55.0, spa: 40.0, spd: 55.0, spe: 60.0},
		abilities: {0: "Sap Sipper", H: "Pickup"},
		heightm: 0.6,
		weightkg: 11.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamedicham: {
		num: 853.0,
		species: "DeltaMedicham",
		types: ['Fairy', 'Ground'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 60.0, def: 75.0, spa: 60.0, spd: 75.0, spe: 80.0},
		abilities: {0: "Sap Sipper", H: "Pickup"},
		heightm: 1.3,
		weightkg: 31.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltanumel: {
		num: 854.0,
		species: "DeltaNumel",
		types: ['Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 60.0, def: 40.0, spa: 65.0, spd: 45.0, spe: 35.0},
		abilities: {0: "Pickup", 1: "Poison Point", H: "Liquid Ooze"},
		heightm: 0.7,
		weightkg: 24.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacamerupt: {
		num: 855.0,
		species: "DeltaCamerupt",
		types: ['Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 100.0, def: 70.0, spa: 105.0, spd: 75.0, spe: 40.0},
		abilities: {0: "Pickup", 1: "Poison Point", H: "Liquid Ooze"},
		heightm: 1.9,
		weightkg: 220.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaplusle: {
		num: 856.0,
		species: "DeltaPlusle",
		types: ['Fire', 'Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 50.0, def: 40.0, spa: 85.0, spd: 75.0, spe: 95.0},
		abilities: {0: "Cute Charm", H: "Pixilate"},
		heightm: 0.4,
		weightkg: 4.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaminun: {
		num: 857.0,
		species: "DeltaMinun",
		types: ['Ice', 'Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 40.0, def: 50.0, spa: 75.0, spd: 85.0, spe: 95.0},
		abilities: {0: "Cute Charm", H: "Pixilate"},
		heightm: 0.4,
		weightkg: 4.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltawailmer: {
		num: 858.0,
		species: "DeltaWailmer",
		types: ['Ice', 'Flying'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 130.0, atk: 70.0, def: 35.0, spa: 70.0, spd: 35.0, spe: 60.0},
		abilities: {0: "Wonder Skin", 1: "Refrigerate", H: "Snow Cloak"},
		heightm: 2.0,
		weightkg: 130.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltawailord: {
		num: 859.0,
		species: "DeltaWailord",
		types: ['Ice', 'Flying'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 170.0, atk: 90.0, def: 45.0, spa: 90.0, spd: 45.0, spe: 60.0},
		abilities: {0: "Wonder Skin", 1: "Refrigerate", H: "Snow Warning"},
		heightm: 14.5,
		weightkg: 398.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltafeebas: {
		num: 860.0,
		species: "DeltaFeebas",
		types: ['Ghost'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 20.0, atk: 15.0, def: 20.0, spa: 10.0, spd: 55.0, spe: 80.0},
		abilities: {0: "Rattled", 1: "Run Away", H: "Spirit Call"},
		heightm: 0.6,
		weightkg: 7.4,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamilotic: {
		num: 861.0,
		species: "DeltaMilotic",
		types: ['Ghost'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 95.0, atk: 60.0, def: 79.0, spa: 100.0, spd: 125.0, spe: 81.0},
		abilities: {0: "Regenerator", 1: "Defiant", H: "Cursed Body"},
		heightm: 6.2,
		weightkg: 162.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaclamperl: {
		num: 862.0,
		species: "DeltaClamperl",
		types: ['Dragon'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 35.0, atk: 65.0, def: 85.0, spa: 74.0, spd: 55.0, spe: 32.0},
		abilities: {0: "Pressure", H: "Battle Armor"},
		heightm: 0.4,
		weightkg: 52.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltahuntail: {
		num: 863.0,
		species: "DeltaHuntail",
		types: ['Dragon', 'Dark'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 55.0, atk: 104.0, def: 105.0, spa: 94.0, spd: 75.0, spe: 52.0},
		abilities: {0: "Pressure", H: "Strong Jaws"},
		heightm: 1.7,
		weightkg: 27.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagorebyss: {
		num: 864.0,
		species: "DeltaGorebyss",
		types: ['Dragon', 'Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 55.0, atk: 84.0, def: 105.0, spa: 114.0, spd: 75.0, spe: 52.0},
		abilities: {0: "Pressure", H: "Marvel Scale"},
		heightm: 1.8,
		weightkg: 22.6,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltabeldumspider: {
		num: 865.0,
		species: "DeltaBeldum(Spider)",
		types: ['Ground', 'Bug'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 40.0, atk: 55.0, def: 80.0, spa: 35.0, spd: 60.0, spe: 30.0},
		abilities: {0: "Poison Touch", 1: "Immunity", H: "Poison Heal"},
		heightm: 0.6,
		weightkg: 47.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltametangspider: {
		num: 866.0,
		species: "DeltaMetang(Spider)",
		types: ['Ground', 'Bug'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 75.0, def: 100.0, spa: 55.0, spd: 80.0, spe: 50.0},
		abilities: {0: "Poison Touch", 1: "Immunity", H: "Poison Heal"},
		heightm: 1.2,
		weightkg: 101.3,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltametagrossspider: {
		num: 867.0,
		species: "DeltaMetagross(Spider)",
		types: ['Ground', 'Bug'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80.0, atk: 135.0, def: 130.0, spa: 95.0, spd: 90.0, spe: 70.0},
		abilities: {0: "Poison Touch", 1: "Immunity", H: "Poison Heal"},
		heightm: 1.5,
		weightkg: 224.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltabeldumruin: {
		num: 868.0,
		species: "DeltaBeldum(Ruin)",
		types: ['Rock', 'Grass'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 40.0, atk: 55.0, def: 80.0, spa: 35.0, spd: 60.0, spe: 30.0},
		abilities: {0: "Sturdy", H: "Rock Head"},
		heightm: 0.6,
		weightkg: 95.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltametangruin: {
		num: 869.0,
		species: "DeltaMetang(Ruin)",
		types: ['Rock', 'Grass'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 75.0, def: 100.0, spa: 55.0, spd: 80.0, spe: 50.0},
		abilities: {0: "Sturdy", H: "Rock Head"},
		heightm: 1.2,
		weightkg: 202.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltametagrossruin: {
		num: 870.0,
		species: "DeltaMetagross(Ruin)",
		types: ['Rock', 'Grass'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80.0, atk: 135.0, def: 130.0, spa: 95.0, spd: 90.0, spe: 70.0},
		abilities: {0: "Sturdy", H: "Rock Head"},
		heightm: 1.6,
		weightkg: 550.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltabuneary: {
		num: 871.0,
		species: "DeltaBuneary",
		types: ['Fighting'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 55.0, atk: 66.0, def: 44.0, spa: 44.0, spd: 56.0, spe: 85.0},
		abilities: {0: "Pickpocket", 1: "Frisk", H: "Limber"},
		heightm: 0.4,
		weightkg: 5.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalopunny: {
		num: 872.0,
		species: "DeltaLopunny",
		types: ['Fighting'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 65.0, atk: 76.0, def: 84.0, spa: 54.0, spd: 96.0, spe: 105.0},
		abilities: {0: "Unburden", 1: "Inner Focus", H: "Limber"},
		heightm: 1.2,
		weightkg: 33.3,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltariolu: {
		num: 873.0,
		species: "DeltaRiolu",
		types: ['Dark'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 40.0, atk: 70.0, def: 40.0, spa: 35.0, spd: 40.0, spe: 60.0},
		abilities: {0: "Justified", 1: "Pressure", H: "Mummy"},
		heightm: 0.7,
		weightkg: 20.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalucario: {
		num: 874.0,
		species: "DeltaLucario",
		types: ['Dark', 'Ground'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 110.0, def: 70.0, spa: 115.0, spd: 70.0, spe: 90.0},
		abilities: {0: "Justified", 1: "Pressure", H: "Mummy"},
		heightm: 1.2,
		weightkg: 54.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacroagunk: {
		num: 875.0,
		species: "DeltaCroagunk",
		types: ['Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 48.0, atk: 61.0, def: 40.0, spa: 61.0, spd: 40.0, spe: 50.0},
		abilities: {0: "Magma Armor", 1: "Blaze", H: "Hustle"},
		heightm: 0.7,
		weightkg: 23.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatoxicroak: {
		num: 876.0,
		species: "DeltaToxicroak",
		types: ['Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 83.0, atk: 106.0, def: 65.0, spa: 86.0, spd: 65.0, spe: 85.0},
		abilities: {0: "Magma Armor", 1: "Blaze", H: "Hustle"},
		heightm: 1.3,
		weightkg: 44.4,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltavenipede: {
		num: 877.0,
		species: "DeltaVenipede",
		types: ['Rock', 'Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 30.0, atk: 45.0, def: 59.0, spa: 30.0, spd: 39.0, spe: 57.0},
		abilities: {0: "Weak Armor", 1: "Magma Armor", H: "Mold Breaker"},
		heightm: 0.4,
		weightkg: 5.3,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltawhirlipede: {
		num: 878.0,
		species: "DeltaWhirlipede",
		types: ['Rock', 'Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 40.0, atk: 55.0, def: 99.0, spa: 40.0, spd: 79.0, spe: 47.0},
		abilities: {0: "Weak Armor", 1: "Magma Armor", H: "Mold Breaker"},
		heightm: 1.2,
		weightkg: 58.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltascolipede: {
		num: 879.0,
		species: "DeltaScolipede",
		types: ['Rock', 'Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 100.0, def: 89.0, spa: 55.0, spd: 69.0, spe: 112.0},
		abilities: {0: "Weak Armor", 1: "Magma Armor", H: "Mold Breaker"},
		heightm: 2.5,
		weightkg: 200.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapetililwater: {
		num: 880.0,
		species: "DeltaPetilil(Water)",
		types: ['Water', 'Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 45.0, atk: 35.0, def: 50.0, spa: 70.0, spd: 50.0, spe: 30.0},
		abilities: {0: "Storm Drain", 1: "Flash Fire", H: "Regenerator"},
		heightm: 0.5,
		weightkg: 6.6,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalilligantwater: {
		num: 881.0,
		species: "DeltaLilligant(Water)",
		types: ['Water', 'Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 60.0, def: 75.0, spa: 110.0, spd: 75.0, spe: 90.0},
		abilities: {0: "Storm Drain", 1: "Flash Fire", H: "Regenerator"},
		heightm: 1.1,
		weightkg: 16.3,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapetililfairy: {
		num: 882.0,
		species: "DeltaPetilil(Fairy)",
		types: ['Fairy', 'Flying'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 45.0, atk: 35.0, def: 50.0, spa: 70.0, spd: 50.0, spe: 30.0},
		abilities: {0: "Serene Grace", 1: "Synchronize", H: "Healer"},
		heightm: 0.508,
		weightkg: 6.62,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalilligantfairy: {
		num: 883.0,
		species: "DeltaLilligant(Fairy)",
		types: ['Fairy', 'Flying'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 60.0, def: 75.0, spa: 110.0, spd: 75.0, spe: 90.0},
		abilities: {0: "Serene Grace", 1: "Synchronize", H: "Healer"},
		heightm: 1.1,
		weightkg: 16.3,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasolosis: {
		num: 884.0,
		species: "DeltaSolosis",
		types: ['Ghost', 'Rock'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 45.0, atk: 30.0, def: 40.0, spa: 105.0, spd: 50.0, spe: 20.0},
		abilities: {0: "Levitate", 1: "Cursed Body", H: "Intimidate"},
		heightm: 0.3,
		weightkg: 1.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaduosion: {
		num: 885.0,
		species: "DeltaDuosion",
		types: ['Ghost', 'Rock'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 65.0, atk: 40.0, def: 50.0, spa: 125.0, spd: 60.0, spe: 30.0},
		abilities: {0: "Levitate", 1: "Cursed Body", H: "Intimidate"},
		heightm: 0.6,
		weightkg: 8.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltareuniclus: {
		num: 886.0,
		species: "DeltaReuniclus",
		types: ['Ghost', 'Rock'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 110.0, atk: 65.0, def: 75.0, spa: 125.0, spd: 85.0, spe: 30.0},
		abilities: {0: "Levitate", 1: "Cursed Body", H: "Intimidate"},
		heightm: 1.0,
		weightkg: 20.1,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadarumaka: {
		num: 887.0,
		species: "DeltaDarumaka",
		types: ['Dark', 'Ghost'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 90.0, def: 45.0, spa: 15.0, spd: 45.0, spe: 50.0},
		abilities: {0: "Unnerve", H: "Wonder Skin"},
		heightm: 0.6,
		weightkg: 37.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadarmanitan: {
		num: 888.0,
		species: "DeltaDarmanitan",
		types: ['Dark', 'Ghost'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 105.0, atk: 140.0, def: 55.0, spa: 30.0, spd: 55.0, spe: 95.0},
		abilities: {0: "Unnerve", H: "Wonder Skin"},
		heightm: 1.3,
		weightkg: 92.9,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamaractus: {
		num: 889.0,
		species: "DeltaMaractus",
		types: ['Steel'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 75.0, atk: 86.0, def: 67.0, spa: 106.0, spd: 67.0, spe: 60.0},
		abilities: {0: "Motor Drive", 1: "Clear Body", H: "Trace"},
		heightm: 1.0,
		weightkg: 28.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadwebbleberry: {
		num: 890.0,
		species: "DeltaDwebble(Berry)",
		types: ['Grass', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 50.0, atk: 65.0, def: 85.0, spa: 35.0, spd: 35.0, spe: 55.0},
		abilities: {0: "Harvest", 1: "Leaf Guard", H: "Chlorophyll"},
		heightm: 0.3,
		weightkg: 14.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacrustleberry: {
		num: 891.0,
		species: "DeltaCrustle(Berry)",
		types: ['Grass', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 95.0, def: 125.0, spa: 65.0, spd: 75.0, spe: 45.0},
		abilities: {0: "Harvest", 1: "Leaf Guard", H: "Chlorophyll"},
		heightm: 1.4,
		weightkg: 150.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadwebblecake: {
		num: 892.0,
		species: "DeltaDwebble(Cake)",
		types: ['Fairy', 'Normal'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 50.0, atk: 65.0, def: 85.0, spa: 35.0, spd: 35.0, spe: 55.0},
		abilities: {0: "Own Tempo", 1: "Scrappy", H: "Simple"},
		heightm: 0.3,
		weightkg: 14.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacrustlecake: {
		num: 893.0,
		species: "DeltaCrustle(Cake)",
		types: ['Fairy', 'Normal'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 95.0, def: 125.0, spa: 65.0, spd: 75.0, spe: 45.0},
		abilities: {0: "Own Tempo", 1: "Scrappy", H: "Simple"},
		heightm: 1.4,
		weightkg: 100.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltayamask: {
		num: 894.0,
		species: "DeltaYamask",
		types: ['Steel', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 38.0, atk: 30.0, def: 85.0, spa: 55.0, spd: 65.0, spe: 30.0},
		abilities: {0: "Aftermath", 1: "Infiltrator", H: "Wonder Skin"},
		heightm: 0.5,
		weightkg: 1.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacofagrigus: {
		num: 895.0,
		species: "DeltaCofagrigus",
		types: ['Steel', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 78.0, atk: 50.0, def: 145.0, spa: 95.0, spd: 105.0, spe: 30.0},
		abilities: {0: "Aftermath", 1: "Infiltrator", H: "Wonder Skin"},
		heightm: 1.7,
		weightkg: 76.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaemolga: {
		num: 896.0,
		species: "DeltaEmolga",
		types: ['Fire', 'Dark'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 55.0, atk: 75.0, def: 60.0, spa: 75.0, spd: 60.0, spe: 103.0},
		abilities: {0: "Flash Fire", H: "Pickup"},
		heightm: 0.4,
		weightkg: 5.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltakarrablast: {
		num: 897.0,
		species: "DeltaKarrablast",
		types: ['Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 50.0, atk: 75.0, def: 45.0, spa: 40.0, spd: 45.0, spe: 60.0},
		abilities: {0: "Gluttony", 1: "Sweet Veil", H: "Simple"},
		heightm: 0.5,
		weightkg: 5.9,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaescavalier: {
		num: 898.0,
		species: "DeltaEscavalier",
		types: ['Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70.0, atk: 135.0, def: 105.0, spa: 60.0, spd: 105.0, spe: 20.0},
		abilities: {0: "Gluttony", 1: "Sweet Veil", H: "Simple"},
		heightm: 1.0,
		weightkg: 33.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltafoongus: {
		num: 899.0,
		species: "DeltaFoongus",
		types: ['Ghost', 'Dark'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 69.0, atk: 55.0, def: 45.0, spa: 55.0, spd: 55.0, spe: 15.0},
		abilities: {0: "Prankster", H: "Intimidate"},
		heightm: 0.2,
		weightkg: 1.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaamoonguss: {
		num: 900.0,
		species: "DeltaAmoonguss",
		types: ['Ghost', 'Dark'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 114.0, atk: 85.0, def: 70.0, spa: 85.0, spd: 80.0, spe: 30.0},
		abilities: {0: "Prankster", H: "Intimidate"},
		heightm: 0.6,
		weightkg: 10.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalitwick: {
		num: 901.0,
		species: "DeltaLitwick",
		types: ['Fairy', 'Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 50.0, atk: 30.0, def: 55.0, spa: 65.0, spd: 55.0, spe: 20.0},
		abilities: {0: "Flash Fire", 1: "Weak Armor", H: "Fairy Aura"},
		heightm: 0.3,
		weightkg: 3.1,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalampent: {
		num: 902.0,
		species: "DeltaLampent",
		types: ['Fairy', 'Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 40.0, def: 60.0, spa: 95.0, spd: 60.0, spe: 55.0},
		abilities: {0: "Flash Fire", 1: "Weak Armor", H: "Fairy Aura"},
		heightm: 0.6,
		weightkg: 13.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltachandelure: {
		num: 903.0,
		species: "DeltaChandelure",
		types: ['Fairy', 'Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 60.0, atk: 55.0, def: 90.0, spa: 145.0, spd: 90.0, spe: 80.0},
		abilities: {0: "Flash Fire", 1: "Weak Armor", H: "Fairy Aura"},
		heightm: 1.0,
		weightkg: 34.3,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaaxew: {
		num: 904.0,
		species: "DeltaAxew",
		types: ['Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 46.0, atk: 87.0, def: 60.0, spa: 30.0, spd: 40.0, spe: 57.0},
		abilities: {0: "Strong Jaw", 1: "Water Veil", H: "Swift Swim"},
		heightm: 0.6,
		weightkg: 18.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltafraxure: {
		num: 905.0,
		species: "DeltaFraxure",
		types: ['Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 66.0, atk: 117.0, def: 70.0, spa: 40.0, spd: 50.0, spe: 67.0},
		abilities: {0: "Strong Jaw", 1: "Water Veil", H: "Swift Swim"},
		heightm: 1.0,
		weightkg: 36.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltahaxorus: {
		num: 906.0,
		species: "DeltaHaxorus",
		types: ['Water', 'Steel'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 76.0, atk: 147.0, def: 90.0, spa: 60.0, spd: 70.0, spe: 97.0},
		abilities: {0: "Strong Jaw", 1: "Water Veil", H: "Heavy Metal"},
		heightm: 1.8,
		weightkg: 105.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagolett: {
		num: 907.0,
		species: "DeltaGolett",
		types: ['Fighting', 'Steel'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 59.0, atk: 74.0, def: 50.0, spa: 35.0, spd: 50.0, spe: 35.0},
		abilities: {0: "Iron Fist", 1: "Battle Armor", H: "Guts"},
		heightm: 1.0,
		weightkg: 92.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagolurk: {
		num: 908.0,
		species: "DeltaGolurk",
		types: ['Fighting', 'Steel'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 89.0, atk: 124.0, def: 80.0, spa: 55.0, spd: 80.0, spe: 55.0},
		abilities: {0: "Iron Fist", 1: "Battle Armor", H: "Guts"},
		heightm: 2.8,
		weightkg: 330.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaheatmor: {
		num: 909.0,
		species: "DeltaHeatmor",
		types: ['Poison', 'Steel'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 85.0, atk: 97.0, def: 66.0, spa: 105.0, spd: 66.0, spe: 65.0},
		abilities: {0: "Liquid Ooze", 1: "Sheer Force", H: "Mega Launcher"},
		heightm: 1.4,
		weightkg: 116.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadeino: {
		num: 910.0,
		species: "DeltaDeino",
		types: ['Ground', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 52.0, atk: 65.0, def: 50.0, spa: 45.0, spd: 50.0, spe: 38.0},
		abilities: {0: "Pickup"},
		heightm: 0.8,
		weightkg: 17.3,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltazweilous: {
		num: 911.0,
		species: "DeltaZweilous",
		types: ['Ground', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 72.0, atk: 85.0, def: 70.0, spa: 65.0, spd: 70.0, spe: 58.0},
		abilities: {0: "Pickup"},
		heightm: 1.4,
		weightkg: 50.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltahydreigon: {
		num: 912.0,
		species: "DeltaHydreigon",
		types: ['Ground', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 92.0, atk: 105.0, def: 90.0, spa: 125.0, spd: 90.0, spe: 98.0},
		abilities: {0: "Pickup"},
		heightm: 1.8,
		weightkg: 160.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalarvesta: {
		num: 913.0,
		species: "DeltaLarvesta",
		types: ['Dark', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 55.0, atk: 85.0, def: 55.0, spa: 50.0, spd: 55.0, spe: 60.0},
		abilities: {0: "Defiant", H: "Pickup"},
		heightm: 1.1,
		weightkg: 28.8,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltavolcarona: {
		num: 914.0,
		species: "DeltaVolcarona",
		types: ['Dark', 'Poison'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 85.0, atk: 60.0, def: 65.0, spa: 135.0, spd: 105.0, spe: 100.0},
		abilities: {0: "Levitate", H: "Pickup"},
		heightm: 1.6,
		weightkg: 46.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaamaura: {
		num: 915.0,
		species: "DeltaAmaura",
		types: ['Grass', 'Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 77.0, atk: 59.0, def: 50.0, spa: 67.0, spd: 63.0, spe: 46.0},
		abilities: {0: "Friend Guard", H: "Pickup"},
		heightm: 1.3,
		weightkg: 25.2,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaaurorus: {
		num: 916.0,
		species: "DeltaAurorus",
		types: ['Grass', 'Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 123.0, atk: 77.0, def: 72.0, spa: 99.0, spd: 92.0, spe: 58.0},
		abilities: {0: "Friend Guard", H: "Pickup"},
		heightm: 2.7,
		weightkg: 225.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagoomy: {
		num: 917.0,
		species: "DeltaGoomy",
		types: ['Ground', 'Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 45.0, atk: 50.0, def: 35.0, spa: 55.0, spd: 75.0, spe: 40.0},
		abilities: {0: "Overcoat", 1: "Water Absorb", H: "Gooey"},
		heightm: 0.3,
		weightkg: 2.8,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasliggoo: {
		num: 918.0,
		species: "DeltaSliggoo",
		types: ['Ground', 'Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 68.0, atk: 75.0, def: 53.0, spa: 83.0, spd: 113.0, spe: 60.0},
		abilities: {0: "Overcoat", 1: "Water Absorb", H: "Gooey"},
		heightm: 0.8,
		weightkg: 17.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagoodra: {
		num: 919.0,
		species: "DeltaGoodra",
		types: ['Ground', 'Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 90.0, atk: 100.0, def: 70.0, spa: 110.0, spd: 150.0, spe: 80.0},
		abilities: {0: "Overcoat", 1: "Water Absorb", H: "Gooey"},
		heightm: 2.0,
		weightkg: 150.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaregirock: {
		num: 920.0,
		species: "DeltaRegirock",
		types: ['Ground'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80.0, atk: 100.0, def: 200.0, spa: 50.0, spd: 100.0, spe: 50.0},
		abilities: {0: "Sand Veil", H: "Dry Skin"},
		heightm: 1.7,
		weightkg: 230.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaregice: {
		num: 921.0,
		species: "DeltaRegice",
		types: ['Water'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80.0, atk: 50.0, def: 100.0, spa: 100.0, spd: 200.0, spe: 50.0},
		abilities: {0: "Water Veil", H: "Storm Drain"},
		heightm: 1.8,
		weightkg: 175.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaregisteel: {
		num: 922.0,
		species: "DeltaRegisteel",
		types: ['Fire'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80.0, atk: 75.0, def: 150.0, spa: 75.0, spd: 150.0, spe: 50.0},
		abilities: {0: "Flame Body", H: "Pickup"},
		heightm: 1.9,
		weightkg: 205.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltameloetta: {
		num: 923.0,
		species: "DeltaMeloetta",
		types: ['Dark', 'Fairy'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 100.0, atk: 128.0, def: 90.0, spa: 77.0, spd: 77.0, spe: 128.0},
		abilities: {0: "Filter"},
		heightm: 0.6,
		weightkg: 6.5,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltahoopa: {
		num: 924.0,
		species: "DeltaHoopa",
		types: ['Flying'],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80.0, atk: 110.0, def: 60.0, spa: 150.0, spd: 130.0, spe: 70.0},
		abilities: {0: "Cloud Nine"},
		heightm: 0.5,
		weightkg: 9.0,
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
};

exports.BattlePokedex = BattlePokedex;