'use strict';

/**@type {{[k: string]: ModdedTemplateData}} */
let BattlePokedex = {
	deltabulbasaur: {
		num: "727",
		species: "DeltaBulbasaur",
		types: ['Fairy', 'Psychic'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "45", atk: "49", def: "49", spa: "65", spd: "65", spe: "45"},
		abilities: {0: "Pickup", H: "Regenerator"},
		heightm: ".7",
		weightkg: "6.9",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaivysaur: {
		num: "728",
		species: "DeltaIvysaur",
		types: ['Fairy', 'Psychic'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "62", def: "63", spa: "80", spd: "80", spe: "60"},
		abilities: {0: "Pickup", 1: "", H: "Regenerator"},
		heightm: "1",
		weightkg: "13.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltavenusaur: {
		num: "729",
		species: "DeltaVenusaur",
		types: ['Fairy', 'Psychic'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "80", atk: "82", def: "83", spa: "100", spd: "100", spe: "80"},
		abilities: {0: "Pickup", H: "Regenerator"},
		heightm: "2",
		weightkg: "100.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacharmander: {
		num: "730",
		species: "DeltaCharmander",
		types: ['Ghost', 'Dragon'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "39", atk: "52", def: "43", spa: "60", spd: "50", spe: "65"},
		abilities: {0: "Pickup", H: "Dark Aura"},
		heightm: ".6",
		weightkg: "8.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacharmeleon: {
		num: "731",
		species: "DeltaCharmeleon",
		types: ['Ghost', 'Dragon'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "58", atk: "64", def: "58", spa: "80", spd: "65", spe: "80"},
		abilities: {0: "Pickup", H: "Dark Aura"},
		heightm: "1.1",
		weightkg: "19",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacharizard: {
		num: "732",
		species: "DeltaCharizard",
		types: ['Ghost', 'Dragon'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "78", atk: "84", def: "78", spa: "109", spd: "85", spe: "100"},
		abilities: {0: "Pickup", H: "Dark Aura"},
		heightm: "1.7",
		weightkg: "90.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasquirtle: {
		num: "733",
		species: "DeltaSquirtle",
		types: ['Dark', 'Fighting'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "44", atk: "48", def: "65", spa: "50", spd: "64", spe: "43"},
		abilities: {0: "Pickup", 1: "", H: "Pickup"},
		heightm: "0.5",
		weightkg: "9.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltawartortle: {
		num: "734",
		species: "DeltaWartortle",
		types: ['Dark', 'Fighting'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "59", atk: "63", def: "80", spa: "65", spd: "80", spe: "58"},
		abilities: {0: "Pickup", 1: "", H: "Pickup"},
		heightm: "1",
		weightkg: "22.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltablastoise: {
		num: "735",
		species: "DeltaBlastoise",
		types: ['Dark', 'Fighting'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "79", atk: "83", def: "100", spa: "85", spd: "105", spe: "78"},
		abilities: {0: "Pickup", 1: "", H: "Pickup"},
		heightm: "1.6",
		weightkg: "85.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapawniard: {
		num: "736",
		species: "DeltaPawniard",
		types: ['Flying', 'Fighting'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "45", atk: "85", def: "70", spa: "40", spd: "40", spe: "60"},
		abilities: {0: "Defiant", 1: "Frisk", H: "Pickup"},
		heightm: ".5",
		weightkg: "10.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltabisharp: {
		num: "737",
		species: "DeltaBisharp",
		types: ['Flying', 'Fighting'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "65", atk: "125", def: "100", spa: "60", spd: "70", spe: "70"},
		abilities: {0: "Frisk", 1: "Defiant", H: "Pickup"},
		heightm: "1.6",
		weightkg: "70.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaralts: {
		num: "738",
		species: "DeltaRalts",
		types: ['Electric', 'Ice'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "28", atk: "25", def: "25", spa: "45", spd: "35", spe: "40"},
		abilities: {0: "Lightning Rod", 1: "Clear Body", H: "Snow Cloak"},
		heightm: "0.4",
		weightkg: "6.6",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltakirlia: {
		num: "739",
		species: "DeltaKirlia",
		types: ['Electric', 'Ice'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "38", atk: "35", def: "35", spa: "65", spd: "55", spe: "50"},
		abilities: {0: "Lightning Rod", 1: "Clear Body", H: "Snow Cloak"},
		heightm: "0.8",
		weightkg: "20.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagardevoir: {
		num: "740",
		species: "DeltaGardevoir",
		types: ['Electric', 'Ice'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "68", atk: "65", def: "65", spa: "125", spd: "115", spe: "80"},
		abilities: {0: "Lightning Rod", 1: "Clear Body", H: "Snow Cloak"},
		heightm: "1.6",
		weightkg: "48.4",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagallade: {
		num: "741",
		species: "DeltaGallade",
		types: ['Electric', 'Ice'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "68", atk: "125", def: "65", spa: "65", spd: "115", spe: "80"},
		abilities: {0: "Volt Absorb", H: "Ice Body"},
		heightm: "1.6",
		weightkg: "52.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasunkern: {
		num: "742",
		species: "DeltaSunkern",
		types: ['Fire', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "30", atk: "30", def: "30", spa: "30", spd: "30", spe: "30"},
		abilities: {0: "Flame Body", 1: "Analytic", H: "Poison Point"},
		heightm: ".3",
		weightkg: "1.8",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasunflora: {
		num: "743",
		species: "DeltaSunflora",
		types: ['Fire', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "75", atk: "75", def: "55", spa: "105", spd: "85", spe: "30"},
		abilities: {0: "Flame Body", 1: "Analytic", H: "Poison Point"},
		heightm: ".8",
		weightkg: "8.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltabergmite: {
		num: "744",
		species: "DeltaBergmite",
		types: ['Rock'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "55", atk: "69", def: "85", spa: "32", spd: "35", spe: "28"},
		abilities: {0: "Solid Rock", 1: "Battle Armor", H: "Sand Stream"},
		heightm: "1.0",
		weightkg: "99.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaavalugg: {
		num: "745",
		species: "DeltaAvalugg",
		types: ['Rock', 'Dragon'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "95", atk: "117", def: "184", spa: "44", spd: "46", spe: "28"},
		abilities: {0: "Solid Rock", 1: "Battle Armor", H: "Sand Stream"},
		heightm: "2.0",
		weightkg: "505.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltascyther: {
		num: "746",
		species: "DeltaScyther",
		types: ['Ice', 'Fighting'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "110", def: "80", spa: "55", spd: "80", spe: "105"},
		abilities: {0: "Hustle", 1: "Pickup", H: "Super Luck"},
		heightm: "1.5",
		weightkg: "56.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltascizor: {
		num: "747",
		species: "DeltaScizor",
		types: ['Ice', 'Fighting'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "130", def: "100", spa: "55", spd: "80", spe: "65"},
		abilities: {0: "Scrappy", 1: "Pickup", H: "Super Luck"},
		heightm: "1.8",
		weightkg: "118",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltascraggy: {
		num: "748",
		species: "DeltaScraggy",
		types: ['Grass'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "50", atk: "75", def: "70", spa: "35", spd: "70", spe: "48"},
		abilities: {0: "Rough Skin", 1: "Rivalry", H: "Anger Point"},
		heightm: "0.6",
		weightkg: "11.8",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltascrafty: {
		num: "749",
		species: "DeltaScrafty",
		types: ['Grass'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "65", atk: "90", def: "115", spa: "45", spd: "115", spe: "58"},
		abilities: {0: "Rough Skin", 1: "Rivalry", H: "Anger Point"},
		heightm: "1.1",
		weightkg: "30.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacombee: {
		num: "750",
		species: "DeltaCombee",
		types: ['Steel', 'fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "30", atk: "30", def: "42", spa: "30", spd: "42", spe: "70"},
		abilities: {0: "Levitate", H: "Speed Boost"},
		heightm: "0.3",
		weightkg: "11.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltavespiquen: {
		num: "751",
		species: "DeltaVespiquen",
		types: ['Steel', 'fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "80", def: "102", spa: "80", spd: "102", spe: "40"},
		abilities: {0: "Levitate", H: "Speed Boost"},
		heightm: "1.2",
		weightkg: "38.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltakoffing: {
		num: "752",
		species: "DeltaKoffing",
		types: ['Electric', 'Flying'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "40", atk: "65", def: "95", spa: "60", spd: "45", spe: "35"},
		abilities: {0: "Cloud Nine", 1: "Pickup", H: "Volt Absorb"},
		heightm: ".6",
		weightkg: "1.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaweezing: {
		num: "753",
		species: "DeltaWeezing",
		types: ['Electric', 'Flying'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "65", atk: "90", def: "120", spa: "85", spd: "70", spe: "60"},
		abilities: {0: "Cloud Nine", 1: "Pickup", H: "Volt Absorb"},
		heightm: "1.2",
		weightkg: "9.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapurrloin: {
		num: "754",
		species: "DeltaPurrloin",
		types: ['Ghost', 'Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "41", atk: "50", def: "37", spa: "50", spd: "37", spe: "66"},
		abilities: {0: "Illusion", 1: "Unnerve", H: "Lightning Rod"},
		heightm: "0.4",
		weightkg: "10.1",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaliepard: {
		num: "755",
		species: "DeltaLiepard",
		types: ['Ghost', 'Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "64", atk: "88", def: "50", spa: "88", spd: "50", spe: "106"},
		abilities: {0: "Illusion", 1: "Unnerve", H: "Bulletproof"},
		heightm: "1.1",
		weightkg: "37.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaphantump: {
		num: "756",
		species: "DeltaPhantump",
		types: ['Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "43", atk: "70", def: "48", spa: "50", spd: "60", spe: "38"},
		abilities: {0: "Snow Warning", 1: "Overcoat", H: "Snow Cloak"},
		heightm: "0.4",
		weightkg: "7.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatrevenant: {
		num: "757",
		species: "DeltaTrevenant",
		types: ['Fairy', 'fighting'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "85", atk: "110", def: "76", spa: "65", spd: "82", spe: "56"},
		abilities: {0: "Snow Warning", 1: "Overcoat", H: "Snow Cloak"},
		heightm: "1.5",
		weightkg: "71.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasnorunt: {
		num: "758",
		species: "DeltaSnorunt",
		types: ['Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "50", atk: "50", def: "50", spa: "50", spd: "50", spe: "50"},
		abilities: {0: "White Smoke", H: "Flash Fire"},
		heightm: "0.7",
		weightkg: "16.8",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaglalie: {
		num: "759",
		species: "DeltaGlalie",
		types: ['Fire', 'rock'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "80", atk: "80", def: "80", spa: "80", spd: "80", spe: "80"},
		abilities: {0: "Rock Head", H: "Flash Fire"},
		heightm: "1.5",
		weightkg: "256.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltafroslass: {
		num: "760",
		species: "DeltaFroslass",
		types: ['Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "80", def: "70", spa: "80", spd: "70", spe: "110"},
		abilities: {0: "Competitive", H: "Flash Fire"},
		heightm: "1.3",
		weightkg: "26.6",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltashinx: {
		num: "761",
		species: "DeltaShinx",
		types: ['Steel', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "45", atk: "65", def: "34", spa: "40", spd: "34", spe: "45"},
		abilities: {0: "Sniper", 1: "Poison Touch", H: "Pickup"},
		heightm: ".5",
		weightkg: "19.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaluxio: {
		num: "762",
		species: "DeltaLuxio",
		types: ['Steel', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "85", def: "49", spa: "60", spd: "49", spe: "60"},
		abilities: {0: "Poison Touch", 1: "Sniper", H: "Pickup"},
		heightm: ".9",
		weightkg: "30.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaluxray: {
		num: "763",
		species: "DeltaLuxray",
		types: ['Steel', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "80", atk: "120", def: "79", spa: "95", spd: "79", spe: "70"},
		abilities: {0: "Poison Touch", 1: "Sniper", H: "Pickup"},
		heightm: "1.4",
		weightkg: "42.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltanoibat: {
		num: "764",
		species: "DeltaNoibat",
		types: ['Grass', 'Steel'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "40", atk: "30", def: "35", spa: "45", spd: "40", spe: "55"},
		abilities: {0: "Chlorophyll", 1: "Natural Cure", H: "Solar Power"},
		heightm: "0.5",
		weightkg: "8.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltanoivern: {
		num: "765",
		species: "DeltaNoivern",
		types: ['Grass', 'Steel'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "85", atk: "70", def: "80", spa: "97", spd: "80", spe: "123"},
		abilities: {0: "Chlorophyll", 1: "Solar Power", H: "Flower Gift"},
		heightm: "1.5",
		weightkg: "85",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltabudew: {
		num: "766",
		species: "DeltaBudew",
		types: ['Dark', 'Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "40", atk: "30", def: "35", spa: "50", spd: "70", spe: "55"},
		abilities: {0: "Pickup", 1: "Pickup", H: "Inner Focus"},
		heightm: "0.2",
		weightkg: "1.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaroselia: {
		num: "767",
		species: "DeltaRoselia",
		types: ['Dark', 'Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "50", atk: "60", def: "45", spa: "100", spd: "80", spe: "65"},
		abilities: {0: "Pickup", 1: "Pickup", H: "Limber"},
		heightm: "0.3",
		weightkg: "2.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaroserade: {
		num: "768",
		species: "DeltaRoserade",
		types: ['Dark', 'Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "70", def: "55", spa: "125", spd: "105", spe: "90"},
		abilities: {0: "Pickup", 1: "Pickup", H: "Limber"},
		heightm: "0.9",
		weightkg: "14.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadrifloon: {
		num: "769",
		species: "DeltaDrifloon",
		types: ['Fire', 'Flying'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "90", atk: "50", def: "34", spa: "60", spd: "44", spe: "70"},
		abilities: {0: "Flash Fire", 1: "Vital Spirit", H: "No Guard"},
		heightm: "0.4",
		weightkg: "1.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadrifblim: {
		num: "770",
		species: "DeltaDrifblim",
		types: ['Fire', 'Flying'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "150", atk: "80", def: "44", spa: "90", spd: "54", spe: "80"},
		abilities: {0: "Flash Fire", 1: "Vital Spirit", H: "No Guard"},
		heightm: "1.2",
		weightkg: "15.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagrimer: {
		num: "771",
		species: "DeltaGrimer",
		types: ['Ground'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "80", atk: "80", def: "50", spa: "40", spd: "50", spe: "25"},
		abilities: {0: "Sap Sipper", H: "Water Absorb"},
		heightm: "0.9",
		weightkg: "30.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamuk: {
		num: "772",
		species: "DeltaMuk",
		types: ['Ground'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "105", atk: "105", def: "75", spa: "65", spd: "100", spe: "50"},
		abilities: {0: "Sap Sipper", 1: "Pickup", H: "Water Absorb"},
		heightm: "1.2",
		weightkg: "30.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltawooper: {
		num: "773",
		species: "DeltaWooper",
		types: ['Grass', 'Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "55", atk: "45", def: "45", spa: "25", spd: "25", spe: "15"},
		abilities: {0: "Pickpocket", 1: "Flash Fire", H: "Harvest"},
		heightm: "0.4",
		weightkg: "8.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaquagsire: {
		num: "774",
		species: "DeltaQuagsire",
		types: ['Grass', 'Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "95", atk: "85", def: "85", spa: "65", spd: "65", spe: "35"},
		abilities: {0: "Pickpocket", 1: "Flash Fire", H: "Harvest"},
		heightm: "1.4",
		weightkg: "75.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamunchlax: {
		num: "775",
		species: "DeltaMunchlax",
		types: ['Grass'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "135", atk: "85", def: "40", spa: "40", spd: "85", spe: "5"},
		abilities: {0: "Overcoat", 1: "Thick Fat", H: "Adaptability"},
		heightm: "0.6",
		weightkg: "105.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasnorlax: {
		num: "776",
		species: "DeltaSnorlax",
		types: ['Grass'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "160", atk: "110", def: "65", spa: "65", spd: "110", spe: "30"},
		abilities: {0: "Overcoat", 1: "Thick Fat", H: "Adaptability"},
		heightm: "2.1",
		weightkg: "460.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamisdreavus: {
		num: "777",
		species: "DeltaMisdreavus",
		types: ['Ice', 'Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "60", def: "60", spa: "85", spd: "85", spe: "85"},
		abilities: {0: "Magic Guard", H: "Pickup"},
		heightm: "0.7",
		weightkg: "1.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamismagius: {
		num: "778",
		species: "DeltaMismagius",
		types: ['Ice', 'Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "60", def: "60", spa: "105", spd: "105", spe: "105"},
		abilities: {0: "Magic Guard", H: "Pickup"},
		heightm: "0.9",
		weightkg: "4.4",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacyndaquil: {
		num: "779",
		species: "DeltaCyndaquil",
		types: ['Electric'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "39", atk: "52", def: "43", spa: "60", spd: "50", spe: "65"},
		abilities: {0: "Static", H: "Lightning Rod"},
		heightm: "0.5",
		weightkg: "7.9",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaquilava: {
		num: "780",
		species: "DeltaQuilava",
		types: ['Electric', 'Steel'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "58", atk: "64", def: "58", spa: "80", spd: "65", spe: "80"},
		abilities: {0: "Static", H: "Lightning Rod"},
		heightm: "0.9",
		weightkg: "28.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatyphlosion: {
		num: "781",
		species: "DeltaTyphlosion",
		types: ['Electric', 'Steel'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "78", atk: "84", def: "78", spa: "109", spd: "85", spe: "100"},
		abilities: {0: "Motor Drive", H: "Lightning Rod"},
		heightm: "1.7",
		weightkg: "159.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatreecko: {
		num: "782",
		species: "DeltaTreecko",
		types: ['Normal', 'Fighting'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "40", atk: "45", def: "35", spa: "65", spd: "55", spe: "70"},
		abilities: {0: "Inner Focus", H: "Iron Fist"},
		heightm: "0.5",
		weightkg: "5.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagrovyle: {
		num: "783",
		species: "DeltaGrovyle",
		types: ['Normal', 'Fighting'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "50", atk: "65", def: "45", spa: "85", spd: "65", spe: "95"},
		abilities: {0: "Inner Focus", H: "Iron Fist"},
		heightm: "0.9",
		weightkg: "21.6",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasceptile: {
		num: "784",
		species: "DeltaSceptile",
		types: ['Dragon', 'Fighting'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "85", def: "65", spa: "105", spd: "85", spe: "120"},
		abilities: {0: "Inner Focus", H: "Iron Fist"},
		heightm: "1.7",
		weightkg: "52.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatorchic: {
		num: "785",
		species: "DeltaTorchic",
		types: ['Psychic'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "45", atk: "60", def: "40", spa: "70", spd: "50", spe: "45"},
		abilities: {0: "Keen Eye", H: "Rivalry"},
		heightm: "0.4",
		weightkg: "2.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacombusken: {
		num: "786",
		species: "DeltaCombusken",
		types: ['Psychic'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "85", def: "60", spa: "85", spd: "60", spe: "55"},
		abilities: {0: "Keen Eye", H: "Rivalry"},
		heightm: "0.9",
		weightkg: "19.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltablaziken: {
		num: "787",
		species: "DeltaBlaziken",
		types: ['Psychic', 'Flying'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "80", atk: "120", def: "70", spa: "110", spd: "70", spe: "80"},
		abilities: {0: "Keen Eye", H: "Gale Wings"},
		heightm: "1.9",
		weightkg: "52.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaturtwig: {
		num: "788",
		species: "DeltaTurtwig",
		types: ['Water', 'Ground'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "55", atk: "68", def: "64", spa: "45", spd: "55", spe: "31"},
		abilities: {0: "Water Absorb", H: "Swift Swim"},
		heightm: "0.4",
		weightkg: "10.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagrotle: {
		num: "789",
		species: "DeltaGrotle",
		types: ['Water', 'Ground'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "75", atk: "89", def: "85", spa: "55", spd: "65", spe: "36"},
		abilities: {0: "Water Absorb", H: "Swift Swim"},
		heightm: "1.1",
		weightkg: "97.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatorterra: {
		num: "790",
		species: "DeltaTorterra",
		types: ['Water', 'Ground'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "95", atk: "109", def: "105", spa: "75", spd: "85", spe: "56"},
		abilities: {0: "Water Absorb", H: "Swift Swim"},
		heightm: "2.2",
		weightkg: "310.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasnivy: {
		num: "791",
		species: "DeltaSnivy",
		types: ['Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "45", atk: "45", def: "55", spa: "45", spd: "55", spe: "63"},
		abilities: {0: "Multiscale", H: "Hydration"},
		heightm: "0.6",
		weightkg: "8.1",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaservine: {
		num: "792",
		species: "DeltaServine",
		types: ['Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "60", def: "75", spa: "60", spd: "75", spe: "83"},
		abilities: {0: "Multiscale", H: "Hydration"},
		heightm: "0.8",
		weightkg: "16.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaserperior: {
		num: "793",
		species: "DeltaSerperior",
		types: ['Water', 'Dragon'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "75", atk: "75", def: "95", spa: "75", spd: "95", spe: "113"},
		abilities: {0: "Multiscale", H: "Drizzle"},
		heightm: "3.3",
		weightkg: "63.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltafroakie: {
		num: "794",
		species: "DeltaFroakie",
		types: ['Grass'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "41", atk: "56", def: "40", spa: "62", spd: "44", spe: "71"},
		abilities: {0: "Steadfast", H: "Prankster"},
		heightm: "0.3",
		weightkg: "7.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltafrogadier: {
		num: "795",
		species: "DeltaFrogadier",
		types: ['Grass'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "54", atk: "63", def: "52", spa: "83", spd: "56", spe: "97"},
		abilities: {0: "Steadfast", H: "Prankster"},
		heightm: "0.6",
		weightkg: "10.9",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagreninja: {
		num: "796",
		species: "DeltaGreninja",
		types: ['Grass', 'Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "72", atk: "95", def: "67", spa: "103", spd: "71", spe: "122"},
		abilities: {0: "Steadfast", H: "Prankster"},
		heightm: "1.5",
		weightkg: "40.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapidgey: {
		num: "797",
		species: "DeltaPidgey",
		types: ['Dark', 'Dragon'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "40", atk: "45", def: "40", spa: "35", spd: "35", spe: "56"},
		abilities: {0: "Intimidate", 1: "Early Bird", H: "Marvel Scale"},
		heightm: "0.3",
		weightkg: "1.8",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapidgeotto: {
		num: "798",
		species: "DeltaPidgeotto",
		types: ['Dark', 'Dragon'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "63", atk: "60", def: "55", spa: "50", spd: "50", spe: "71"},
		abilities: {0: "Intimidate", 1: "Early Bird", H: "Marvel Scale"},
		heightm: "1.1",
		weightkg: "30",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapidgeot: {
		num: "799",
		species: "DeltaPidgeot",
		types: ['Dark', 'Dragon'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "83", atk: "80", def: "75", spa: "70", spd: "70", spe: "101"},
		abilities: {0: "Intimidate", 1: "Keen Eye", H: "Marvel Scale"},
		heightm: "1.5",
		weightkg: "39.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadiglett: {
		num: "800",
		species: "DeltaDiglett",
		types: ['Ice', 'Normal'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "10", atk: "55", def: "25", spa: "35", spd: "45", spe: "95"},
		abilities: {0: "Snow Cloak", 1: "Pickup", H: "Fur Coat"},
		heightm: "0.2",
		weightkg: "0.8",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadugtrio: {
		num: "801",
		species: "DeltaDugtrio",
		types: ['Ice', 'Normal'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "35", atk: "80", def: "50", spa: "50", spd: "70", spe: "120"},
		abilities: {0: "Snow Cloak", 1: "Pickup", H: "Fur Coat"},
		heightm: "0.7",
		weightkg: "33.3",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagrowlithe: {
		num: "802",
		species: "DeltaGrowlithe",
		types: ['Normal', 'Dragon'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "55", atk: "70", def: "45", spa: "70", spd: "50", spe: "60"},
		abilities: {0: "Inner Focus", 1: "Intimidate", H: "Multiscale"},
		heightm: "0.7",
		weightkg: "19.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaarcanine: {
		num: "803",
		species: "DeltaArcanine",
		types: ['Normal', 'Dragon'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "90", atk: "110", def: "80", spa: "100", spd: "80", spe: "95"},
		abilities: {0: "Inner Focus", 1: "Intimidate", H: "Multiscale"},
		heightm: "1.9",
		weightkg: "155.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltageodude: {
		num: "804",
		species: "DeltaGeodude",
		types: ['Psychic', 'Rock'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "40", atk: "80", def: "100", spa: "30", spd: "30", spe: "20"},
		abilities: {0: "Regenerator", 1: "Sap Sipper", H: "Magic Bounce"},
		heightm: "0.4",
		weightkg: "20.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagraveler: {
		num: "805",
		species: "DeltaGraveler",
		types: ['Psychic', 'Rock'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "55", atk: "95", def: "115", spa: "45", spd: "45", spe: "35"},
		abilities: {0: "Regenerator", 1: "Sap Sipper", H: "Magic Bounce"},
		heightm: "1.0",
		weightkg: "105.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagolem: {
		num: "806",
		species: "DeltaGolem",
		types: ['Psychic', 'Rock'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "80", atk: "120", def: "130", spa: "55", spd: "65", spe: "45"},
		abilities: {0: "Regenerator", 1: "Sap Sipper", H: "Magic Bounce"},
		heightm: "1.4",
		weightkg: "300.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatentacool: {
		num: "807",
		species: "DeltaTentacool",
		types: ['Grass', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "40", atk: "40", def: "35", spa: "50", spd: "100", spe: "70"},
		abilities: {0: "Regenerator", 1: "Poison Touch", H: "Overgrow"},
		heightm: "0.9",
		weightkg: "45.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatentacruel: {
		num: "808",
		species: "DeltaTentacruel",
		types: ['Grass', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "80", atk: "70", def: "65", spa: "80", spd: "120", spe: "100"},
		abilities: {0: "Regenerator", 1: "Poison Touch", H: "Overgrow"},
		heightm: "1.6",
		weightkg: "55.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadoduo: {
		num: "809",
		species: "DeltaDoduo",
		types: ['Psychic'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "35", atk: "85", def: "45", spa: "35", spd: "35", spe: "75"},
		abilities: {0: "Compoundeyes", 1: "Trace", H: "Pickup"},
		heightm: "1.4",
		weightkg: "39.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadodrio: {
		num: "810",
		species: "DeltaDodrio",
		types: ['Psychic'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "110", def: "70", spa: "60", spd: "60", spe: "100"},
		abilities: {0: "Compoundeyes", 1: "Trace", H: "Pickup"},
		heightm: "1.8",
		weightkg: "85.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatangela: {
		num: "811",
		species: "DeltaTangela",
		types: ['Ground'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "65", atk: "55", def: "115", spa: "100", spd: "40", spe: "60"},
		abilities: {0: "Dry Skin", 1: "Sand Force", H: "Rough Skin"},
		heightm: "1.0",
		weightkg: "35.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatangrowth: {
		num: "812",
		species: "DeltaTangrowth",
		types: ['Ground', 'Fighting'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "100", atk: "100", def: "125", spa: "110", spd: "50", spe: "50"},
		abilities: {0: "Dry Skin", 1: "Sand Force", H: "Rough Skin"},
		heightm: "2.0",
		weightkg: "128.6",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaditto: {
		num: "813",
		species: "DeltaDitto",
		types: ['Normal'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "48", atk: "48", def: "48", spa: "48", spd: "48", spe: "48"},
		abilities: {0: "Protean"},
		heightm: "0.3",
		weightkg: "4.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltakabuto: {
		num: "814",
		species: "DeltaKabuto",
		types: ['Bug', 'Dark'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "30", atk: "80", def: "95", spa: "55", spd: "45", spe: "55"},
		abilities: {0: "Swarm", 1: "Unnerve", H: "Tough Claws"},
		heightm: "0.5",
		weightkg: "11.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltakabutops: {
		num: "815",
		species: "DeltaKabutops",
		types: ['Bug', 'Dark'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "115", def: "105", spa: "65", spd: "70", spe: "80"},
		abilities: {0: "Swarm", 1: "Unnerve", H: "Tough Claws"},
		heightm: "1.3",
		weightkg: "40.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadratini: {
		num: "816",
		species: "DeltaDratini",
		types: ['Electric', 'Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "41", atk: "64", def: "45", spa: "50", spd: "50", spe: "50"},
		abilities: {0: "Swift Swim", H: "Volt Absorb"},
		heightm: "1.8",
		weightkg: "3.3",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadragonair: {
		num: "817",
		species: "DeltaDragonair",
		types: ['Electric', 'Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "61", atk: "84", def: "65", spa: "70", spd: "70", spe: "70"},
		abilities: {0: "Swift Swim", H: "Volt Absorb"},
		heightm: "4.0",
		weightkg: "16.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadragonite: {
		num: "818",
		species: "DeltaDragonite",
		types: ['Electric', 'Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "91", atk: "134", def: "95", spa: "100", spd: "100", spe: "80"},
		abilities: {0: "Swift Swim", H: "Volt Absorb"},
		heightm: "2.2",
		weightkg: "210.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltahoothoot: {
		num: "819",
		species: "DeltaHoothoot",
		types: ['Ice', 'Flying'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "30", def: "30", spa: "36", spd: "56", spe: "50"},
		abilities: {0: "Snow Cloak", 1: "Keen Eye", H: "No Guard"},
		heightm: "0.7",
		weightkg: "21.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltanoctowl: {
		num: "820",
		species: "DeltaNoctowl",
		types: ['Ice', 'Flying'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "100", atk: "50", def: "50", spa: "76", spd: "96", spe: "70"},
		abilities: {0: "Snow Cloak", 1: "Keen Eye", H: "No Guard"},
		heightm: "1.6",
		weightkg: "40.8",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltachinchou: {
		num: "821",
		species: "DeltaChinchou",
		types: ['Ghost', 'Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "75", atk: "38", def: "38", spa: "56", spd: "56", spe: "67"},
		abilities: {0: "Flash Fire", 1: "Illuminate", H: "Levitate"},
		heightm: "0.5",
		weightkg: "12.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalanturn: {
		num: "822",
		species: "DeltaLanturn",
		types: ['Ghost', 'Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "125", atk: "58", def: "58", spa: "76", spd: "76", spe: "67"},
		abilities: {0: "Flash Fire", 1: "Illuminate", H: "Levitate"},
		heightm: "1.2",
		weightkg: "22.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapichu: {
		num: "823",
		species: "DeltaPichu",
		types: ['Flying', 'Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "20", atk: "40", def: "15", spa: "35", spd: "35", spe: "60"},
		abilities: {0: "Cute Charm", 1: "Cloud Nine", H: "Gale Wings"},
		heightm: "0.3",
		weightkg: "2.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapikachu: {
		num: "824",
		species: "DeltaPikachu",
		types: ['Flying', 'Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "35", atk: "55", def: "30", spa: "50", spd: "40", spe: "90"},
		abilities: {0: "Cute Charm", 1: "Cloud Nine", H: "Gale Wings"},
		heightm: "0.4",
		weightkg: "6.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaraichu: {
		num: "825",
		species: "DeltaRaichu",
		types: ['Flying', 'Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "90", def: "55", spa: "90", spd: "80", spe: "110"},
		abilities: {0: "Cute Charm", 1: "Cloud Nine", H: "Gale Wings"},
		heightm: "0.8",
		weightkg: "30.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaaipom: {
		num: "826",
		species: "DeltaAipom",
		types: ['Ghost', 'Normal'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "55", atk: "70", def: "55", spa: "40", spd: "55", spe: "85"},
		abilities: {0: "Cursed Body", 1: "Rattled", H: "Technician"},
		heightm: "0.8",
		weightkg: "11.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaambipom: {
		num: "827",
		species: "DeltaAmbipom",
		types: ['Ghost', 'Normal'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "75", atk: "100", def: "66", spa: "60", spd: "66", spe: "115"},
		abilities: {0: "Cursed Body", 1: "Infiltrator", H: "Technician"},
		heightm: "1.2",
		weightkg: "20.3",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltayanma: {
		num: "828",
		species: "DeltaYanma",
		types: ['Grass', 'Flying'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "65", atk: "65", def: "45", spa: "75", spd: "45", spe: "95"},
		abilities: {0: "Adaptability", 1: "Leaf Guard", H: "Natural Cure"},
		heightm: "1.2",
		weightkg: "38.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltayanmega: {
		num: "829",
		species: "DeltaYanmega",
		types: ['Grass', 'Flying'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "86", atk: "76", def: "86", spa: "116", spd: "56", spe: "95"},
		abilities: {0: "Adaptability", 1: "Chlorophyll", H: "Natural Cure"},
		heightm: "1.9",
		weightkg: "51.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagirafarig: {
		num: "830",
		species: "DeltaGirafarig",
		types: ['Steel', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "80", def: "65", spa: "90", spd: "65", spe: "85"},
		abilities: {0: "Anger Point", 1: "Stench", H: "Intimidate"},
		heightm: "1.5",
		weightkg: "41.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadunsparce: {
		num: "831",
		species: "DeltaDunsparce",
		types: ['Bug', 'Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "100", atk: "70", def: "70", spa: "65", spd: "65", spe: "45"},
		abilities: {0: "Hyper Cutter", 1: "Swift Swim", H: "Skill Link"},
		heightm: "1.5",
		weightkg: "14.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltashuckle: {
		num: "832",
		species: "DeltaShuckle",
		types: ['Fighting', 'Steel'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "20", atk: "10", def: "230", spa: "10", spd: "230", spe: "5"},
		abilities: {0: "Sturdy", 1: "No Guard", H: "Iron Barbs"},
		heightm: "0.6",
		weightkg: "20.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaremoraid: {
		num: "833",
		species: "DeltaRemoraid",
		types: ['Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "35", atk: "65", def: "35", spa: "65", spd: "35", spe: "65"},
		abilities: {0: "Heatproof", 1: "White Smoke", H: "Contrary"},
		heightm: "0.6",
		weightkg: "12.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaoctillery: {
		num: "834",
		species: "DeltaOctillery",
		types: ['Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "75", atk: "105", def: "75", spa: "105", spd: "75", spe: "45"},
		abilities: {0: "Heatproof", 1: "White Smoke", H: "Contrary"},
		heightm: "0.9",
		weightkg: "28.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaelekid: {
		num: "835",
		species: "DeltaElekid",
		types: ['Rock'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "45", atk: "63", def: "37", spa: "65", spd: "55", spe: "95"},
		abilities: {0: "Inner Focus", H: "Battle Armor"},
		heightm: "0.6",
		weightkg: "23.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaelectabuzz: {
		num: "836",
		species: "DeltaElectabuzz",
		types: ['Rock'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "65", atk: "83", def: "57", spa: "95", spd: "85", spe: "105"},
		abilities: {0: "Inner Focus", H: "Battle Armor"},
		heightm: "1.1",
		weightkg: "30.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaelectivire: {
		num: "837",
		species: "DeltaElectivire",
		types: ['Rock', 'Dragon'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "75", atk: "123", def: "67", spa: "95", spd: "85", spe: "95"},
		abilities: {0: "Pickup", H: "Sturdy"},
		heightm: "1.8",
		weightkg: "138.6",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamagby: {
		num: "838",
		species: "DeltaMagby",
		types: ['Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "45", atk: "75", def: "37", spa: "70", spd: "55", spe: "83"},
		abilities: {0: "Swift Swim", H: "Rain Dish"},
		heightm: "0.7",
		weightkg: "21.4",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamagmar: {
		num: "839",
		species: "DeltaMagmar",
		types: ['Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "65", atk: "95", def: "57", spa: "100", spd: "85", spe: "93"},
		abilities: {0: "Swift Swim", H: "Rain Dish"},
		heightm: "1.3",
		weightkg: "44.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamagmortar: {
		num: "840",
		species: "DeltaMagmortar",
		types: ['Water', 'Steel'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "75", atk: "95", def: "67", spa: "125", spd: "95", spe: "83"},
		abilities: {0: "Mega Launcher", H: "Filter"},
		heightm: "1.6",
		weightkg: "68.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalotad: {
		num: "841",
		species: "DeltaLotad",
		types: ['Psychic', 'Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "40", atk: "30", def: "30", spa: "40", spd: "50", spe: "30"},
		abilities: {0: "Magic Bounce", 1: "Synchronize", H: "Unaware"},
		heightm: "0.5",
		weightkg: "2.6",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalombre: {
		num: "842",
		species: "DeltaLombre",
		types: ['Psychic', 'Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "50", def: "50", spa: "60", spd: "70", spe: "50"},
		abilities: {0: "Magic Bounce", 1: "Synchronize", H: "Unaware"},
		heightm: "1.2",
		weightkg: "32.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaludicolo: {
		num: "843",
		species: "DeltaLudicolo",
		types: ['Psychic', 'Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "80", atk: "70", def: "70", spa: "90", spd: "100", spe: "70"},
		abilities: {0: "Magic Bounce", 1: "Synchronize", H: "Unaware"},
		heightm: "1.5",
		weightkg: "55.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaseedot: {
		num: "844",
		species: "DeltaSeedot",
		types: ['Electric'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "40", atk: "40", def: "50", spa: "30", spd: "30", spe: "30"},
		abilities: {0: "Volt Absorb", 1: "Minus", H: "Competitive"},
		heightm: "0.5",
		weightkg: "4.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltanuzleaf: {
		num: "845",
		species: "DeltaNuzleaf",
		types: ['Electric'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "70", def: "40", spa: "60", spd: "40", spe: "60"},
		abilities: {0: "Volt Absorb", 1: "Minus", H: "Competitive"},
		heightm: "1.0",
		weightkg: "28.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltashiftry: {
		num: "846",
		species: "DeltaShiftry",
		types: ['Electric'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "90", atk: "100", def: "60", spa: "90", spd: "60", spe: "80"},
		abilities: {0: "Volt Absorb", 1: "Minus", H: "Competitive"},
		heightm: "1.3",
		weightkg: "59.6",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasableye: {
		num: "847",
		species: "DeltaSableye",
		types: ['Fire', 'Rock'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "50", atk: "75", def: "75", spa: "65", spd: "65", spe: "50"},
		abilities: {0: "Solid Rock", 1: "Weak Armor", H: "Unburden"},
		heightm: "0.5",
		weightkg: "11.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamawile: {
		num: "848",
		species: "DeltaMawile",
		types: ['Grass', 'Dark'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "50", atk: "85", def: "85", spa: "55", spd: "55", spe: "50"},
		abilities: {0: "Serene Grace", 1: "Aroma Veil", H: "Immunity"},
		heightm: "0.6",
		weightkg: "11.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaaron: {
		num: "849",
		species: "DeltaAron",
		types: ['Fire', 'Steel'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "50", atk: "70", def: "100", spa: "40", spd: "40", spe: "30"},
		abilities: {0: "Flame Body", 1: "Drought", H: "Heavy Metal"},
		heightm: "0.4",
		weightkg: "60.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalairon: {
		num: "850",
		species: "DeltaLairon",
		types: ['Fire', 'Steel'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "90", def: "140", spa: "50", spd: "50", spe: "40"},
		abilities: {0: "Flame Body", 1: "Drought", H: "Heavy Metal"},
		heightm: "0.9",
		weightkg: "120.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaaggron: {
		num: "851",
		species: "DeltaAggron",
		types: ['Fire', 'Steel'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "110", def: "180", spa: "60", spd: "60", spe: "50"},
		abilities: {0: "Flame Body", 1: "Drought", H: "Heavy Metal"},
		heightm: "2.1",
		weightkg: "360.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltameditite: {
		num: "852",
		species: "DeltaMeditite",
		types: ['Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "30", atk: "40", def: "55", spa: "40", spd: "55", spe: "60"},
		abilities: {0: "Sap Sipper", H: "Pickup"},
		heightm: "0.6",
		weightkg: "11.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamedicham: {
		num: "853",
		species: "DeltaMedicham",
		types: ['Fairy', 'Ground'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "60", def: "75", spa: "60", spd: "75", spe: "80"},
		abilities: {0: "Sap Sipper", H: "Pickup"},
		heightm: "1.3",
		weightkg: "31.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltanumel: {
		num: "854",
		species: "DeltaNumel",
		types: ['Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "60", def: "40", spa: "65", spd: "45", spe: "35"},
		abilities: {0: "Pickup", 1: "Poison Point", H: "Liquid Ooze"},
		heightm: "0.7",
		weightkg: "24.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacamerupt: {
		num: "855",
		species: "DeltaCamerupt",
		types: ['Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "100", def: "70", spa: "105", spd: "75", spe: "40"},
		abilities: {0: "Pickup", 1: "Poison Point", H: "Liquid Ooze"},
		heightm: "1.9",
		weightkg: "220.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaplusle: {
		num: "856",
		species: "DeltaPlusle",
		types: ['Fire', 'Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "50", def: "40", spa: "85", spd: "75", spe: "95"},
		abilities: {0: "Cute Charm", H: "Pixilate"},
		heightm: "0.4",
		weightkg: "4.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaminun: {
		num: "857",
		species: "DeltaMinun",
		types: ['Ice', 'Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "40", def: "50", spa: "75", spd: "85", spe: "95"},
		abilities: {0: "Cute Charm", H: "Pixilate"},
		heightm: "0.4",
		weightkg: "4.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltawailmer: {
		num: "858",
		species: "DeltaWailmer",
		types: ['Ice', 'Flying'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "130", atk: "70", def: "35", spa: "70", spd: "35", spe: "60"},
		abilities: {0: "Wonder Skin", 1: "Refrigerate", H: "Snow Cloak"},
		heightm: "2.0",
		weightkg: "130.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltawailord: {
		num: "859",
		species: "DeltaWailord",
		types: ['Ice', 'Flying'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "170", atk: "90", def: "45", spa: "90", spd: "45", spe: "60"},
		abilities: {0: "Wonder Skin", 1: "Refrigerate", H: "Snow Warning"},
		heightm: "14.5",
		weightkg: "398.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltafeebas: {
		num: "860",
		species: "DeltaFeebas",
		types: ['Ghost'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "20", atk: "15", def: "20", spa: "10", spd: "55", spe: "80"},
		abilities: {0: "Rattled", 1: "Run Away", H: "Pickup"},
		heightm: "0.6",
		weightkg: "7.4",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamilotic: {
		num: "861",
		species: "DeltaMilotic",
		types: ['Ghost'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "95", atk: "60", def: "79", spa: "100", spd: "125", spe: "81"},
		abilities: {0: "Regenerator", 1: "Defiant", H: "Cursed Body"},
		heightm: "6.2",
		weightkg: "162.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaclamperl: {
		num: "862",
		species: "DeltaClamperl",
		types: ['Dragon'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "35", atk: "65", def: "85", spa: "74", spd: "55", spe: "32"},
		abilities: {0: "Pressure", H: "Battle Armor"},
		heightm: "0.40",
		weightkg: "52.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltahuntail: {
		num: "863",
		species: "DeltaHuntail",
		types: ['Dragon', 'Dark'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "55", atk: "104", def: "105", spa: "94", spd: "75", spe: "52"},
		abilities: {0: "Pressure", H: "Strong Jaws"},
		heightm: "1.70",
		weightkg: "27.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagorebyss: {
		num: "864",
		species: "DeltaGorebyss",
		types: ['Dragon', 'Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "55", atk: "84", def: "105", spa: "114", spd: "75", spe: "52"},
		abilities: {0: "Pressure", H: "Marvel Scale"},
		heightm: "1.80",
		weightkg: "22.6",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltabeldumspider: {
		num: "865",
		species: "DeltaBeldum(Spider)",
		types: ['Ground', 'Bug'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "40", atk: "55", def: "80", spa: "35", spd: "60", spe: "30"},
		abilities: {0: "Poison Touch", 1: "Immunity", H: "Poison Heal"},
		heightm: "0.6",
		weightkg: "47.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltametangspider: {
		num: "866",
		species: "DeltaMetang(Spider)",
		types: ['Ground', 'Bug'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "75", def: "100", spa: "55", spd: "80", spe: "50"},
		abilities: {0: "Poison Touch", 1: "Immunity", H: "Poison Heal"},
		heightm: "1.2",
		weightkg: "101.3",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltametagrossspider: {
		num: "867",
		species: "DeltaMetagross(Spider)",
		types: ['Ground', 'Bug'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "80", atk: "135", def: "130", spa: "95", spd: "90", spe: "70"},
		abilities: {0: "Poison Touch", 1: "Immunity", H: "Poison Heal"},
		heightm: "1.5",
		weightkg: "224",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltabeldumruin: {
		num: "868",
		species: "DeltaBeldum(Ruin)",
		types: ['Rock', 'Grass'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "40", atk: "55", def: "80", spa: "35", spd: "60", spe: "30"},
		abilities: {0: "Sturdy", H: "Rock Head"},
		heightm: "0.6",
		weightkg: "95.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltametangruin: {
		num: "869",
		species: "DeltaMetang(Ruin)",
		types: ['Rock', 'Grass'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "75", def: "100", spa: "55", spd: "80", spe: "50"},
		abilities: {0: "Sturdy", H: "Rock Head"},
		heightm: "1.2",
		weightkg: "202.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltametagrossruin: {
		num: "870",
		species: "DeltaMetagross(Ruin)",
		types: ['Rock', 'Grass'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "80", atk: "135", def: "130", spa: "95", spd: "90", spe: "70"},
		abilities: {0: "Sturdy", H: "Rock Head"},
		heightm: "1.6",
		weightkg: "550.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltabuneary: {
		num: "871",
		species: "DeltaBuneary",
		types: ['Fighting'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "55", atk: "66", def: "44", spa: "44", spd: "56", spe: "85"},
		abilities: {0: "Pickpocket", 1: "Frisk", H: "Limber"},
		heightm: "0.4",
		weightkg: "5.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalopunny: {
		num: "872",
		species: "DeltaLopunny",
		types: ['Fighting'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "65", atk: "76", def: "84", spa: "54", spd: "96", spe: "105"},
		abilities: {0: "Unburden", 1: "Inner Focus", H: "Limber"},
		heightm: "1.2",
		weightkg: "33.3",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltariolu: {
		num: "873",
		species: "DeltaRiolu",
		types: ['Dark'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "40", atk: "70", def: "40", spa: "35", spd: "40", spe: "60"},
		abilities: {0: "Justified", 1: "Pressure", H: "Mummy"},
		heightm: "0.7",
		weightkg: "20.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalucario: {
		num: "874",
		species: "DeltaLucario",
		types: ['Dark', 'Ground'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "110", def: "70", spa: "115", spd: "70", spe: "90"},
		abilities: {0: "Justified", 1: "Pressure", H: "Mummy"},
		heightm: "1.2",
		weightkg: "54.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacroagunk: {
		num: "875",
		species: "DeltaCroagunk",
		types: ['Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "48", atk: "61", def: "40", spa: "61", spd: "40", spe: "50"},
		abilities: {0: "Magma Armor", 1: "Blaze", H: "Hustle"},
		heightm: "0.7",
		weightkg: "23.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltatoxicroak: {
		num: "876",
		species: "DeltaToxicroak",
		types: ['Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "83", atk: "106", def: "65", spa: "86", spd: "65", spe: "85"},
		abilities: {0: "Magma Armor", 1: "Blaze", H: "Hustle"},
		heightm: "1.3",
		weightkg: "44.4",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltavenipede: {
		num: "877",
		species: "DeltaVenipede",
		types: ['Rock', 'Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "30", atk: "45", def: "59", spa: "30", spd: "39", spe: "57"},
		abilities: {0: "Weak Armor", 1: "Magma Armor", H: "Mold Breaker"},
		heightm: "0.4",
		weightkg: "5.3",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltawhirlipede: {
		num: "878",
		species: "DeltaWhirlipede",
		types: ['Rock', 'Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "40", atk: "55", def: "99", spa: "40", spd: "79", spe: "47"},
		abilities: {0: "Weak Armor", 1: "Magma Armor", H: "Mold Breaker"},
		heightm: "1.2",
		weightkg: "58.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltascolipede: {
		num: "879",
		species: "DeltaScolipede",
		types: ['Rock', 'Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "100", def: "89", spa: "55", spd: "69", spe: "112"},
		abilities: {0: "Weak Armor", 1: "Magma Armor", H: "Mold Breaker"},
		heightm: "2.5",
		weightkg: "200.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapetililwater: {
		num: "880",
		species: "DeltaPetilil(Water)",
		types: ['Water', 'Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "45", atk: "35", def: "50", spa: "70", spd: "50", spe: "30"},
		abilities: {0: "Storm Drain", 1: "Flash Fire", H: "Regenerator"},
		heightm: "0.5",
		weightkg: "6.6",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalilligantwater: {
		num: "881",
		species: "DeltaLilligant(Water)",
		types: ['Water', 'Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "60", def: "75", spa: "110", spd: "75", spe: "90"},
		abilities: {0: "Storm Drain", 1: "Flash Fire", H: "Regenerator"},
		heightm: "1.1",
		weightkg: "16.3",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltapetililfairy: {
		num: "882",
		species: "DeltaPetilil(Fairy)",
		types: ['Fairy', 'Flying'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "45", atk: "35", def: "50", spa: "70", spd: "50", spe: "30"},
		abilities: {0: "Serene Grace", 1: "Synchronize", H: "Healer"},
		heightm: ".508",
		weightkg: "6.62",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalilligantfairy: {
		num: "883",
		species: "DeltaLilligant(Fairy)",
		types: ['Fairy', 'Flying'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "60", def: "75", spa: "110", spd: "75", spe: "90"},
		abilities: {0: "Serene Grace", 1: "Synchronize", H: "Healer"},
		heightm: "1.1",
		weightkg: "16.3",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasolosis: {
		num: "884",
		species: "DeltaSolosis",
		types: ['Ghost', 'Rock'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "45", atk: "30", def: "40", spa: "105", spd: "50", spe: "20"},
		abilities: {0: "Levitate", 1: "Cursed Body", H: "Intimidate"},
		heightm: "0.3",
		weightkg: "1.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaduosion: {
		num: "885",
		species: "DeltaDuosion",
		types: ['Ghost', 'Rock'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "65", atk: "40", def: "50", spa: "125", spd: "60", spe: "30"},
		abilities: {0: "Levitate", 1: "Cursed Body", H: "Intimidate"},
		heightm: "0.6",
		weightkg: "8.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltareuniclus: {
		num: "886",
		species: "DeltaReuniclus",
		types: ['Ghost', 'Rock'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "110", atk: "65", def: "75", spa: "125", spd: "85", spe: "30"},
		abilities: {0: "Levitate", 1: "Cursed Body", H: "Intimidate"},
		heightm: "1.0",
		weightkg: "20.1",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadarumaka: {
		num: "887",
		species: "DeltaDarumaka",
		types: ['Dark', 'Ghost'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "90", def: "45", spa: "15", spd: "45", spe: "50"},
		abilities: {0: "Unnerve", H: "Wonder Skin"},
		heightm: "0.6",
		weightkg: "37.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadarmanitan: {
		num: "888",
		species: "DeltaDarmanitan",
		types: ['Dark', 'Ghost'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "105", atk: "140", def: "55", spa: "30", spd: "55", spe: "95"},
		abilities: {0: "Unnerve", H: "Wonder Skin"},
		heightm: "1.3",
		weightkg: "92.9",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltamaractus: {
		num: "889",
		species: "DeltaMaractus",
		types: ['Steel'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "75", atk: "86", def: "67", spa: "106", spd: "67", spe: "60"},
		abilities: {0: "Motor Drive", 1: "Clear Body", H: "Trace"},
		heightm: "1.0",
		weightkg: "28.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadwebbleberry: {
		num: "890",
		species: "DeltaDwebble(Berry)",
		types: ['Grass', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "50", atk: "65", def: "85", spa: "35", spd: "35", spe: "55"},
		abilities: {0: "Harvest", 1: "Leaf Guard", H: "Chlorophyll"},
		heightm: "0.3",
		weightkg: "14.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacrustleberry: {
		num: "891",
		species: "DeltaCrustle(Berry)",
		types: ['Grass', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "95", def: "125", spa: "65", spd: "75", spe: "45"},
		abilities: {0: "Harvest", 1: "Leaf Guard", H: "Chlorophyll"},
		heightm: "1.4",
		weightkg: "150.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadwebblecake: {
		num: "892",
		species: "DeltaDwebble(Cake)",
		types: ['Fairy', 'Normal'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "50", atk: "65", def: "85", spa: "35", spd: "35", spe: "55"},
		abilities: {0: "Own Tempo", 1: "Scrappy", H: "Simple"},
		heightm: "0.3",
		weightkg: "14.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacrustlecake: {
		num: "893",
		species: "DeltaCrustle(Cake)",
		types: ['Fairy', 'Normal'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "95", def: "125", spa: "65", spd: "75", spe: "45"},
		abilities: {0: "Own Tempo", 1: "Scrappy", H: "Simple"},
		heightm: "1.4",
		weightkg: "100.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltayamask: {
		num: "894",
		species: "DeltaYamask",
		types: ['Steel', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "38", atk: "30", def: "85", spa: "55", spd: "65", spe: "30"},
		abilities: {0: "Aftermath", 1: "Infiltrator", H: "Wonder Skin"},
		heightm: "0.5",
		weightkg: "1.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltacofagrigus: {
		num: "895",
		species: "DeltaCofagrigus",
		types: ['Steel', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "78", atk: "50", def: "145", spa: "95", spd: "105", spe: "30"},
		abilities: {0: "Aftermath", 1: "Infiltrator", H: "Wonder Skin"},
		heightm: "1.7",
		weightkg: "76.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaemolga: {
		num: "896",
		species: "DeltaEmolga",
		types: ['Fire', 'Dark'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "55", atk: "75", def: "60", spa: "75", spd: "60", spe: "103"},
		abilities: {0: "Flash Fire", H: "Pickup"},
		heightm: "0.4",
		weightkg: "5.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltakarrablast: {
		num: "897",
		species: "DeltaKarrablast",
		types: ['Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "50", atk: "75", def: "45", spa: "40", spd: "45", spe: "60"},
		abilities: {0: "Gluttony", 1: "Sweet Veil", H: "Simple"},
		heightm: "0.5",
		weightkg: "5.9",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaescavalier: {
		num: "898",
		species: "DeltaEscavalier",
		types: ['Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "70", atk: "135", def: "105", spa: "60", spd: "105", spe: "20"},
		abilities: {0: "Gluttony", 1: "Sweet Veil", H: "Simple"},
		heightm: "1.0",
		weightkg: "33.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltafoongus: {
		num: "899",
		species: "DeltaFoongus",
		types: ['Ghost', 'Dark'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "69", atk: "55", def: "45", spa: "55", spd: "55", spe: "15"},
		abilities: {0: "Prankster", H: "Intimidate"},
		heightm: "0.2",
		weightkg: "1.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaamoonguss: {
		num: "900",
		species: "DeltaAmoonguss",
		types: ['Ghost', 'Dark'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "114", atk: "85", def: "70", spa: "85", spd: "80", spe: "30"},
		abilities: {0: "Prankster", H: "Intimidate"},
		heightm: "0.6",
		weightkg: "10.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalitwick: {
		num: "901",
		species: "DeltaLitwick",
		types: ['Fairy', 'Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "50", atk: "30", def: "55", spa: "65", spd: "55", spe: "20"},
		abilities: {0: "Flash Fire", 1: "Weak Armor", H: "Fairy Aura"},
		heightm: "0.3",
		weightkg: "3.1",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalampent: {
		num: "902",
		species: "DeltaLampent",
		types: ['Fairy', 'Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "40", def: "60", spa: "95", spd: "60", spe: "55"},
		abilities: {0: "Flash Fire", 1: "Weak Armor", H: "Fairy Aura"},
		heightm: "0.6",
		weightkg: "13.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltachandelure: {
		num: "903",
		species: "DeltaChandelure",
		types: ['Fairy', 'Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "60", atk: "55", def: "90", spa: "145", spd: "90", spe: "80"},
		abilities: {0: "Flash Fire", 1: "Weak Armor", H: "Fairy Aura"},
		heightm: "1.0",
		weightkg: "34.3",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaaxew: {
		num: "904",
		species: "DeltaAxew",
		types: ['Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "46", atk: "87", def: "60", spa: "30", spd: "40", spe: "57"},
		abilities: {0: "Strong Jaw", 1: "Water Veil", H: "Swift Swim"},
		heightm: "0.6",
		weightkg: "18.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltafraxure: {
		num: "905",
		species: "DeltaFraxure",
		types: ['Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "66", atk: "117", def: "70", spa: "40", spd: "50", spe: "67"},
		abilities: {0: "Strong Jaw", 1: "Water Veil", H: "Swift Swim"},
		heightm: "1.0",
		weightkg: "36.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltahaxorus: {
		num: "906",
		species: "DeltaHaxorus",
		types: ['Water', 'Steel'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "76", atk: "147", def: "90", spa: "60", spd: "70", spe: "97"},
		abilities: {0: "Strong Jaw", 1: "Water Veil", H: "Heavy Metal"},
		heightm: "1.8",
		weightkg: "105.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagolett: {
		num: "907",
		species: "DeltaGolett",
		types: ['Fighting', 'Steel'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "59", atk: "74", def: "50", spa: "35", spd: "50", spe: "35"},
		abilities: {0: "Iron Fist", 1: "Battle Armor", H: "Guts"},
		heightm: "1.0",
		weightkg: "92.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagolurk: {
		num: "908",
		species: "DeltaGolurk",
		types: ['Fighting', 'Steel'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "89", atk: "124", def: "80", spa: "55", spd: "80", spe: "55"},
		abilities: {0: "Iron Fist", 1: "Battle Armor", H: "Guts"},
		heightm: "2.8",
		weightkg: "330.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaheatmor: {
		num: "909",
		species: "DeltaHeatmor",
		types: ['Poison', 'Steel'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "85", atk: "97", def: "66", spa: "105", spd: "66", spe: "65"},
		abilities: {0: "Liquid Ooze", 1: "Sheer Force", H: "Mega Launcher"},
		heightm: "1.40",
		weightkg: "116.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltadeino: {
		num: "910",
		species: "DeltaDeino",
		types: ['Ground', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "52", atk: "65", def: "50", spa: "45", spd: "50", spe: "38"},
		abilities: {0: "Pickup"},
		heightm: "0.8",
		weightkg: "17.3",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltazweilous: {
		num: "911",
		species: "DeltaZweilous",
		types: ['Ground', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "72", atk: "85", def: "70", spa: "65", spd: "70", spe: "58"},
		abilities: {0: "Pickup"},
		heightm: "1.4",
		weightkg: "50.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltahydreigon: {
		num: "912",
		species: "DeltaHydreigon",
		types: ['Ground', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "92", atk: "105", def: "90", spa: "125", spd: "90", spe: "98"},
		abilities: {0: "Pickup"},
		heightm: "1.8",
		weightkg: "160.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltalarvesta: {
		num: "913",
		species: "DeltaLarvesta",
		types: ['Dark', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "55", atk: "85", def: "55", spa: "50", spd: "55", spe: "60"},
		abilities: {0: "Defiant", H: "Pickup"},
		heightm: "1.1",
		weightkg: "28.8",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltavolcarona: {
		num: "914",
		species: "DeltaVolcarona",
		types: ['Dark', 'Poison'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "85", atk: "60", def: "65", spa: "135", spd: "105", spe: "100"},
		abilities: {0: "Levitate", H: "Pickup"},
		heightm: "1.6",
		weightkg: "46.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaamaura: {
		num: "915",
		species: "DeltaAmaura",
		types: ['Grass', 'Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "77", atk: "59", def: "50", spa: "67", spd: "63", spe: "46"},
		abilities: {0: "Friend Guard", H: "Pickup"},
		heightm: "1.3",
		weightkg: "25.2",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaaurorus: {
		num: "916",
		species: "DeltaAurorus",
		types: ['Grass', 'Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "123", atk: "77", def: "72", spa: "99", spd: "92", spe: "58"},
		abilities: {0: "Friend Guard", H: "Pickup"},
		heightm: "2.7",
		weightkg: "225.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagoomy: {
		num: "917",
		species: "DeltaGoomy",
		types: ['Ground', 'Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "45", atk: "50", def: "35", spa: "55", spd: "75", spe: "40"},
		abilities: {0: "Overcoat", 1: "Water Absorb", H: "Gooey"},
		heightm: "0.3",
		weightkg: "2.8",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltasliggoo: {
		num: "918",
		species: "DeltaSliggoo",
		types: ['Ground', 'Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "68", atk: "75", def: "53", spa: "83", spd: "113", spe: "60"},
		abilities: {0: "Overcoat", 1: "Water Absorb", H: "Gooey"},
		heightm: "0.8",
		weightkg: "17.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltagoodra: {
		num: "919",
		species: "DeltaGoodra",
		types: ['Ground', 'Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "90", atk: "100", def: "70", spa: "110", spd: "150", spe: "80"},
		abilities: {0: "Overcoat", 1: "Water Absorb", H: "Gooey"},
		heightm: "2.0",
		weightkg: "150.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaregirock: {
		num: "920",
		species: "DeltaRegirock",
		types: ['Ground'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "80", atk: "100", def: "200", spa: "50", spd: "100", spe: "50"},
		abilities: {0: "Sand Veil", H: "Dry Skin"},
		heightm: "1.7",
		weightkg: "230.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaregice: {
		num: "921",
		species: "DeltaRegice",
		types: ['Water'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "80", atk: "50", def: "100", spa: "100", spd: "200", spe: "50"},
		abilities: {0: "Water Veil", H: "Storm Drain"},
		heightm: "1.8",
		weightkg: "175.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltaregisteel: {
		num: "922",
		species: "DeltaRegisteel",
		types: ['Fire'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "80", atk: "75", def: "150", spa: "75", spd: "150", spe: "50"},
		abilities: {0: "Flame Body", H: "Pickup"},
		heightm: "1.9",
		weightkg: "205.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltameloetta: {
		num: "923",
		species: "DeltaMeloetta",
		types: ['Dark', 'Fairy'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "100", atk: "128", def: "90", spa: "77", spd: "77", spe: "128"},
		abilities: {0: "Filter"},
		heightm: "0.6",
		weightkg: "6.5",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
	deltahoopa: {
		num: "924",
		species: "DeltaHoopa",
		types: ['Flying'],
		genderRatio: {M: "0.5", F: "0.5"},
		baseStats: {hp: "80", atk: "110", def: "60", spa: "150", spd: "130", spe: "70"},
		abilities: {0: "Cloud Nine"},
		heightm: "0.5",
		weightkg: "9.0",
		color: "Green",
		eggGroups: ['Undiscovered'],
	},
};

exports.BattlePokedex = BattlePokedex;
